mod; DD.MM.YYYY; HH:MM:SS; free
src; "ManuellErstellt"; "19.04.2024"; "10:08:12";
chs; "ISO8859-1"
ver; "1.0"
tbl; MÜLLABFUHRSPAẞ
com; hier verwende ich das große ß, das weder in ASCII noch in ISO8859-1 enthalten ist. Dies muss zu einer Fehlermeldung führen.
com; com als Befehl ist gueltig und beschreibt einen gewöhnlichen Kommentar
atr; BASIS_VERSION; FZG_NR; FZG_TYP_NR; POLKENN; UNTERNEHMEN; FZG_ADR_STRING; FZG_TECH_NR
frm; num[9.0]; num[4.0]; num[3.0]; char[20]; num[3.0]; char[20]; num[6.0]
end; 0
eof; 1
