"""This file was generated by xsdata, v24.1, on 2024-01-25 13:18:17

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""
from eflips.ingest.xmldata.bvg_xml import (
    ErgebnisReturnCode,
    FahrtFahrgastrelevant,
    Linienfahrplan,
    MeldungMeldungskategorie,
    MeldungMeldungsnummer,
    MeldungMeldungstext,
    NetzpunktNetzpunkttyp,
    NetzpunktMitFahrgastwechsel,
    ParameterName,
    PunktFahrgastwechsel,
    PunktVeroeffentlicht,
    RouteHauptroute,
    RouteRichtung,
    StreckeAuftraggeber,
    T41Auftraggeber,
    T41Veroeffentlicht,
)

__all__ = [
    "ErgebnisReturnCode",
    "FahrtFahrgastrelevant",
    "Linienfahrplan",
    "MeldungMeldungskategorie",
    "MeldungMeldungsnummer",
    "MeldungMeldungstext",
    "NetzpunktNetzpunkttyp",
    "NetzpunktMitFahrgastwechsel",
    "ParameterName",
    "PunktFahrgastwechsel",
    "PunktVeroeffentlicht",
    "RouteHauptroute",
    "RouteRichtung",
    "StreckeAuftraggeber",
    "T41Auftraggeber",
    "T41Veroeffentlicht",
]
