"""This file was generated by xsdata, v24.1, on 2024-01-24 17:18:38

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""
from dataclasses import dataclass, field
from decimal import Decimal
from enum import Enum
from typing import Optional

__NAMESPACE__ = "http://www.ivu.de/mb/intf/passengercount/remote/model/"


class ErgebnisReturnCode(Enum):
    VALUE_0 = 0
    VALUE_1 = 1


class FahrtFahrgastrelevant(Enum):
    J = "J"
    N = "N"


class MeldungMeldungskategorie(Enum):
    VALUE_0 = 0
    VALUE_2 = 2


class MeldungMeldungsnummer(Enum):
    VALUE_0 = 0
    VALUE_18 = 18
    VALUE_5 = 5


class MeldungMeldungstext(Enum):
    ANFRAGE_WURDE_KORREKT_ABGEARBEITET = "Anfrage wurde korrekt abgearbeitet."
    KEINE_UML_UFE_VORHANDEN = "Keine Umläufe vorhanden."
    KEINE_G_LTIGE_LINIE = "Keine gültige Linie."


class NetzpunktNetzpunkttyp(Enum):
    APKT = "APkt"
    BPUNKT = "BPunkt"
    EPKT = "EPkt"
    GPKT = "GPkt"
    HST = "Hst"


class NetzpunktMitFahrgastwechsel(Enum):
    J = "J"
    N = "N"


class ParameterName(Enum):
    BETRIEBSBEREICH = "Betriebsbereich"
    KEINE_ANZEIGEDATEN = "KeineAnzeigedaten"
    KEINE_GUELTIGKEITEN = "KeineGueltigkeiten"
    LINIE = "Linie"
    MELDUNGSKATEGORIE = "Meldungskategorie"
    STICHTAG = "Stichtag"


class PunktFahrgastwechsel(Enum):
    J = "J"
    N = "N"


class PunktVeroeffentlicht(Enum):
    J = "J"
    N = "N"


class RouteHauptroute(Enum):
    J = "J"
    N = "N"


class RouteRichtung(Enum):
    VALUE_0 = 0
    VALUE_1 = 1
    VALUE_2 = 2


class StreckeAuftraggeber(Enum):
    VALUE_1 = 1


class T41Auftraggeber(Enum):
    VALUE_1 = 1


class T41Veroeffentlicht(Enum):
    J = "J"
    N = "N"


@dataclass
class Linienfahrplan:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    generierung: Optional["Linienfahrplan.Generierung"] = field(
        default=None,
        metadata={
            "name": "Generierung",
            "type": "Element",
            "required": True,
        },
    )
    streckennetz_daten: Optional["Linienfahrplan.StreckennetzDaten"] = field(
        default=None,
        metadata={
            "name": "StreckennetzDaten",
            "type": "Element",
        },
    )
    linien_daten: Optional["Linienfahrplan.LinienDaten"] = field(
        default=None,
        metadata={
            "name": "LinienDaten",
            "type": "Element",
        },
    )
    fahrt_daten: Optional["Linienfahrplan.FahrtDaten"] = field(
        default=None,
        metadata={
            "name": "FahrtDaten",
            "type": "Element",
        },
    )
    fahrzeugumlauf_daten: Optional["Linienfahrplan.FahrzeugumlaufDaten"] = field(
        default=None,
        metadata={
            "name": "FahrzeugumlaufDaten",
            "type": "Element",
        },
    )

    @dataclass
    class Generierung:
        startzeitpunkt: Optional[str] = field(
            default=None,
            metadata={
                "name": "Startzeitpunkt",
                "type": "Element",
                "required": True,
            },
        )
        schnittstellenversion: Optional[
            "Linienfahrplan.Generierung.Schnittstellenversion"
        ] = field(
            default=None,
            metadata={
                "name": "Schnittstellenversion",
                "type": "Element",
                "required": True,
            },
        )
        datenversion: Optional["Linienfahrplan.Generierung.Datenversion"] = field(
            default=None,
            metadata={
                "name": "Datenversion",
                "type": "Element",
                "required": True,
            },
        )
        ergebnis: Optional["Linienfahrplan.Generierung.Ergebnis"] = field(
            default=None,
            metadata={
                "name": "Ergebnis",
                "type": "Element",
                "required": True,
            },
        )
        generierungs_parameter: Optional[
            "Linienfahrplan.Generierung.GenerierungsParameter"
        ] = field(
            default=None,
            metadata={
                "name": "GenerierungsParameter",
                "type": "Element",
                "required": True,
            },
        )

        @dataclass
        class Schnittstellenversion:
            version: Optional[Decimal] = field(
                default=None,
                metadata={
                    "name": "Version",
                    "type": "Element",
                    "required": True,
                },
            )
            release: Optional[str] = field(
                default=None,
                metadata={
                    "name": "Release",
                    "type": "Element",
                    "required": True,
                },
            )
            build: Optional[str] = field(
                default=None,
                metadata={
                    "name": "Build",
                    "type": "Element",
                    "required": True,
                },
            )

        @dataclass
        class Datenversion:
            deployment_id: Optional[str] = field(
                default=None,
                metadata={
                    "name": "deploymentID",
                    "type": "Element",
                    "required": True,
                },
            )

        @dataclass
        class Ergebnis:
            return_code: Optional[ErgebnisReturnCode] = field(
                default=None,
                metadata={
                    "name": "ReturnCode",
                    "type": "Element",
                    "required": True,
                },
            )
            meldungsliste: Optional[
                "Linienfahrplan.Generierung.Ergebnis.Meldungsliste"
            ] = field(
                default=None,
                metadata={
                    "name": "Meldungsliste",
                    "type": "Element",
                    "required": True,
                },
            )

            @dataclass
            class Meldungsliste:
                meldung: Optional[
                    "Linienfahrplan.Generierung.Ergebnis.Meldungsliste.Meldung"
                ] = field(
                    default=None,
                    metadata={
                        "name": "Meldung",
                        "type": "Element",
                        "required": True,
                    },
                )

                @dataclass
                class Meldung:
                    meldungskategorie: Optional[MeldungMeldungskategorie] = field(
                        default=None,
                        metadata={
                            "name": "Meldungskategorie",
                            "type": "Element",
                            "required": True,
                        },
                    )
                    meldungsnummer: Optional[MeldungMeldungsnummer] = field(
                        default=None,
                        metadata={
                            "name": "Meldungsnummer",
                            "type": "Element",
                            "required": True,
                        },
                    )
                    meldungstext: Optional[MeldungMeldungstext] = field(
                        default=None,
                        metadata={
                            "name": "Meldungstext",
                            "type": "Element",
                            "required": True,
                        },
                    )

        @dataclass
        class GenerierungsParameter:
            parameter: list[
                "Linienfahrplan.Generierung.GenerierungsParameter.Parameter"
            ] = field(
                default_factory=list,
                metadata={
                    "name": "Parameter",
                    "type": "Element",
                    "min_occurs": 1,
                },
            )

            @dataclass
            class Parameter:
                name: Optional[ParameterName] = field(
                    default=None,
                    metadata={
                        "name": "Name",
                        "type": "Element",
                        "required": True,
                    },
                )
                wert: Optional[str] = field(
                    default=None,
                    metadata={
                        "name": "Wert",
                        "type": "Element",
                        "required": True,
                    },
                )

    @dataclass
    class StreckennetzDaten:
        haltestellenbereiche: Optional[
            "Linienfahrplan.StreckennetzDaten.Haltestellenbereiche"
        ] = field(
            default=None,
            metadata={
                "name": "Haltestellenbereiche",
                "type": "Element",
                "required": True,
            },
        )
        netzpunkte: Optional["Linienfahrplan.StreckennetzDaten.Netzpunkte"] = field(
            default=None,
            metadata={
                "name": "Netzpunkte",
                "type": "Element",
                "required": True,
            },
        )
        gebietskoerperschaften: Optional[
            "Linienfahrplan.StreckennetzDaten.Gebietskoerperschaften"
        ] = field(
            default=None,
            metadata={
                "name": "Gebietskoerperschaften",
                "type": "Element",
                "required": True,
            },
        )
        strecken: Optional["Linienfahrplan.StreckennetzDaten.Strecken"] = field(
            default=None,
            metadata={
                "name": "Strecken",
                "type": "Element",
                "required": True,
            },
        )

        @dataclass
        class Haltestellenbereiche:
            haltestellenbereich: list[
                "Linienfahrplan.StreckennetzDaten.Haltestellenbereiche.Haltestellenbereich"
            ] = field(
                default_factory=list,
                metadata={
                    "name": "Haltestellenbereich",
                    "type": "Element",
                },
            )

            @dataclass
            class Haltestellenbereich:
                nummer: Optional[int] = field(
                    default=None,
                    metadata={
                        "name": "Nummer",
                        "type": "Element",
                        "required": True,
                    },
                )
                kurzname: Optional[str] = field(
                    default=None,
                    metadata={
                        "name": "Kurzname",
                        "type": "Element",
                        "required": True,
                    },
                )
                fahrplanbuchname: Optional[str] = field(
                    default=None,
                    metadata={
                        "name": "Fahrplanbuchname",
                        "type": "Element",
                        "required": True,
                    },
                )

        @dataclass
        class Netzpunkte:
            netzpunkt: list[
                "Linienfahrplan.StreckennetzDaten.Netzpunkte.Netzpunkt"
            ] = field(
                default_factory=list,
                metadata={
                    "name": "Netzpunkt",
                    "type": "Element",
                },
            )

            @dataclass
            class Netzpunkt:
                nummer: Optional[int] = field(
                    default=None,
                    metadata={
                        "name": "Nummer",
                        "type": "Element",
                        "required": True,
                    },
                )
                kurzname: Optional[str] = field(
                    default=None,
                    metadata={
                        "name": "Kurzname",
                        "type": "Element",
                        "required": True,
                    },
                )
                langname: Optional[str] = field(
                    default=None,
                    metadata={
                        "name": "Langname",
                        "type": "Element",
                        "required": True,
                    },
                )
                netzpunkttyp: Optional[NetzpunktNetzpunkttyp] = field(
                    default=None,
                    metadata={
                        "name": "Netzpunkttyp",
                        "type": "Element",
                        "required": True,
                    },
                )
                xkoordinate: Optional[int] = field(
                    default=None,
                    metadata={
                        "name": "Xkoordinate",
                        "type": "Element",
                        "required": True,
                    },
                )
                ykoordinate: Optional[int] = field(
                    default=None,
                    metadata={
                        "name": "Ykoordinate",
                        "type": "Element",
                        "required": True,
                    },
                )
                haltestellenbereich: Optional[int] = field(
                    default=None,
                    metadata={
                        "name": "Haltestellenbereich",
                        "type": "Element",
                    },
                )
                mit_fahrgastwechsel: Optional[NetzpunktMitFahrgastwechsel] = field(
                    default=None,
                    metadata={
                        "name": "mitFahrgastwechsel",
                        "type": "Element",
                        "required": True,
                    },
                )
                gebietskoerperschaften: Optional[
                    "Linienfahrplan.StreckennetzDaten.Netzpunkte.Netzpunkt.Gebietskoerperschaften"
                ] = field(
                    default=None,
                    metadata={
                        "name": "Gebietskoerperschaften",
                        "type": "Element",
                        "required": True,
                    },
                )

                @dataclass
                class Gebietskoerperschaften:
                    gebietskoerperschaft: list[str] = field(
                        default_factory=list,
                        metadata={
                            "name": "Gebietskoerperschaft",
                            "type": "Element",
                        },
                    )

        @dataclass
        class Gebietskoerperschaften:
            gebietskoerperschaft: list[
                "Linienfahrplan.StreckennetzDaten.Gebietskoerperschaften.Gebietskoerperschaft"
            ] = field(
                default_factory=list,
                metadata={
                    "name": "Gebietskoerperschaft",
                    "type": "Element",
                },
            )

            @dataclass
            class Gebietskoerperschaft:
                kurzname: Optional[str] = field(
                    default=None,
                    metadata={
                        "name": "Kurzname",
                        "type": "Element",
                        "required": True,
                    },
                )
                langname: Optional[str] = field(
                    default=None,
                    metadata={
                        "name": "Langname",
                        "type": "Element",
                        "required": True,
                    },
                )

        @dataclass
        class Strecken:
            strecke: list["Linienfahrplan.StreckennetzDaten.Strecken.Strecke"] = field(
                default_factory=list,
                metadata={
                    "name": "Strecke",
                    "type": "Element",
                },
            )

            @dataclass
            class Strecke:
                id: Optional[int] = field(
                    default=None,
                    metadata={
                        "name": "ID",
                        "type": "Element",
                        "required": True,
                    },
                )
                startpunkt: Optional[int] = field(
                    default=None,
                    metadata={
                        "name": "Startpunkt",
                        "type": "Element",
                        "required": True,
                    },
                )
                endpunkt: Optional[int] = field(
                    default=None,
                    metadata={
                        "name": "Endpunkt",
                        "type": "Element",
                        "required": True,
                    },
                )
                streckenlaenge: Optional[int] = field(
                    default=None,
                    metadata={
                        "name": "Streckenlaenge",
                        "type": "Element",
                        "required": True,
                    },
                )
                zwischenpunkte: Optional[
                    "Linienfahrplan.StreckennetzDaten.Strecken.Strecke.Zwischenpunkte"
                ] = field(
                    default=None,
                    metadata={
                        "name": "Zwischenpunkte",
                        "type": "Element",
                        "required": True,
                    },
                )

                @dataclass
                class Zwischenpunkte:
                    zwischenpunkt: Optional[
                        "Linienfahrplan.StreckennetzDaten.Strecken.Strecke.Zwischenpunkte.Zwischenpunkt"
                    ] = field(
                        default=None,
                        metadata={
                            "name": "Zwischenpunkt",
                            "type": "Element",
                        },
                    )

                    @dataclass
                    class Zwischenpunkt:
                        netzpunkt: Optional[int] = field(
                            default=None,
                            metadata={
                                "name": "Netzpunkt",
                                "type": "Element",
                                "required": True,
                            },
                        )
                        entfernung_vom_start: Optional[int] = field(
                            default=None,
                            metadata={
                                "name": "EntfernungVomStart",
                                "type": "Element",
                                "required": True,
                            },
                        )

    @dataclass
    class LinienDaten:
        linie: Optional["Linienfahrplan.LinienDaten.Linie"] = field(
            default=None,
            metadata={
                "name": "Linie",
                "type": "Element",
                "required": True,
            },
        )

        @dataclass
        class Linie:
            kurzname: Optional[str] = field(
                default=None,
                metadata={
                    "name": "Kurzname",
                    "type": "Element",
                    "required": True,
                },
            )
            zugeordnete_betriebshoefe: Optional[
                "Linienfahrplan.LinienDaten.Linie.ZugeordneteBetriebshoefe"
            ] = field(
                default=None,
                metadata={
                    "name": "zugeordneteBetriebshoefe",
                    "type": "Element",
                    "required": True,
                },
            )
            routen_daten: Optional[
                "Linienfahrplan.LinienDaten.Linie.RoutenDaten"
            ] = field(
                default=None,
                metadata={
                    "name": "RoutenDaten",
                    "type": "Element",
                    "required": True,
                },
            )
            routenvarianten: Optional[
                "Linienfahrplan.LinienDaten.Linie.Routenvarianten"
            ] = field(
                default=None,
                metadata={
                    "name": "Routenvarianten",
                    "type": "Element",
                    "required": True,
                },
            )

            @dataclass
            class ZugeordneteBetriebshoefe:
                betriebshof: list[int] = field(
                    default_factory=list,
                    metadata={
                        "name": "Betriebshof",
                        "type": "Element",
                    },
                )

            @dataclass
            class RoutenDaten:
                route: list[
                    "Linienfahrplan.LinienDaten.Linie.RoutenDaten.Route"
                ] = field(
                    default_factory=list,
                    metadata={
                        "name": "Route",
                        "type": "Element",
                    },
                )

                @dataclass
                class Route:
                    lfd_nr: Optional[int] = field(
                        default=None,
                        metadata={
                            "name": "LfdNr",
                            "type": "Element",
                            "required": True,
                        },
                    )
                    externe_routennummer: Optional[int] = field(
                        default=None,
                        metadata={
                            "name": "externeRoutennummer",
                            "type": "Element",
                            "required": True,
                        },
                    )
                    richtung: Optional[RouteRichtung] = field(
                        default=None,
                        metadata={
                            "name": "Richtung",
                            "type": "Element",
                            "required": True,
                        },
                    )
                    hauptroute: Optional[RouteHauptroute] = field(
                        default=None,
                        metadata={
                            "name": "Hauptroute",
                            "type": "Element",
                            "required": True,
                        },
                    )
                    zielanzeigen: Optional[
                        "Linienfahrplan.LinienDaten.Linie.RoutenDaten.Route.Zielanzeigen"
                    ] = field(
                        default=None,
                        metadata={
                            "name": "Zielanzeigen",
                            "type": "Element",
                            "required": True,
                        },
                    )
                    streckenfolge: Optional[
                        "Linienfahrplan.LinienDaten.Linie.RoutenDaten.Route.Streckenfolge"
                    ] = field(
                        default=None,
                        metadata={
                            "name": "Streckenfolge",
                            "type": "Element",
                            "required": True,
                        },
                    )
                    punktfolge: Optional[
                        "Linienfahrplan.LinienDaten.Linie.RoutenDaten.Route.Punktfolge"
                    ] = field(
                        default=None,
                        metadata={
                            "name": "Punktfolge",
                            "type": "Element",
                            "required": True,
                        },
                    )
                    fahrzeitprofile: Optional[
                        "Linienfahrplan.LinienDaten.Linie.RoutenDaten.Route.Fahrzeitprofile"
                    ] = field(
                        default=None,
                        metadata={
                            "name": "Fahrzeitprofile",
                            "type": "Element",
                            "required": True,
                        },
                    )

                    @dataclass
                    class Zielanzeigen:
                        zielanzeige: list[
                            "Linienfahrplan.LinienDaten.Linie.RoutenDaten.Route.Zielanzeigen.Zielanzeige"
                        ] = field(
                            default_factory=list,
                            metadata={
                                "name": "Zielanzeige",
                                "type": "Element",
                            },
                        )

                        @dataclass
                        class Zielanzeige:
                            nummer: Optional[int] = field(
                                default=None,
                                metadata={
                                    "name": "Nummer",
                                    "type": "Element",
                                    "required": True,
                                },
                            )
                            anzeige_text: Optional[str] = field(
                                default=None,
                                metadata={
                                    "name": "AnzeigeText",
                                    "type": "Element",
                                    "required": True,
                                },
                            )

                    @dataclass
                    class Streckenfolge:
                        strecke: list[
                            "Linienfahrplan.LinienDaten.Linie.RoutenDaten.Route.Streckenfolge.Strecke"
                        ] = field(
                            default_factory=list,
                            metadata={
                                "name": "Strecke",
                                "type": "Element",
                                "min_occurs": 1,
                            },
                        )

                        @dataclass
                        class Strecke:
                            lfd_nr: Optional[int] = field(
                                default=None,
                                metadata={
                                    "name": "LfdNr",
                                    "type": "Element",
                                    "required": True,
                                },
                            )
                            strecken_id: Optional[int] = field(
                                default=None,
                                metadata={
                                    "name": "StreckenID",
                                    "type": "Element",
                                    "required": True,
                                },
                            )
                            auftraggeber: Optional[StreckeAuftraggeber] = field(
                                default=None,
                                metadata={
                                    "name": "Auftraggeber",
                                    "type": "Element",
                                },
                            )

                    @dataclass
                    class Punktfolge:
                        punkt: list[
                            "Linienfahrplan.LinienDaten.Linie.RoutenDaten.Route.Punktfolge.Punkt"
                        ] = field(
                            default_factory=list,
                            metadata={
                                "name": "Punkt",
                                "type": "Element",
                                "min_occurs": 1,
                            },
                        )

                        @dataclass
                        class Punkt:
                            lfd_nr: Optional[int] = field(
                                default=None,
                                metadata={
                                    "name": "LfdNr",
                                    "type": "Element",
                                    "required": True,
                                },
                            )
                            netzpunkt: Optional[int] = field(
                                default=None,
                                metadata={
                                    "name": "Netzpunkt",
                                    "type": "Element",
                                    "required": True,
                                },
                            )
                            fahrgastwechsel: Optional[PunktFahrgastwechsel] = field(
                                default=None,
                                metadata={
                                    "name": "Fahrgastwechsel",
                                    "type": "Element",
                                    "required": True,
                                },
                            )
                            veroeffentlicht: Optional[PunktVeroeffentlicht] = field(
                                default=None,
                                metadata={
                                    "type": "Element",
                                    "required": True,
                                },
                            )
                            zielanzeige: Optional[int] = field(
                                default=None,
                                metadata={
                                    "name": "Zielanzeige",
                                    "type": "Element",
                                },
                            )

                    @dataclass
                    class Fahrzeitprofile:
                        fahrzeitprofil: list[
                            "Linienfahrplan.LinienDaten.Linie.RoutenDaten.Route.Fahrzeitprofile.Fahrzeitprofil"
                        ] = field(
                            default_factory=list,
                            metadata={
                                "name": "Fahrzeitprofil",
                                "type": "Element",
                                "min_occurs": 1,
                            },
                        )

                        @dataclass
                        class Fahrzeitprofil:
                            fahrzeitprofil_nummer: Optional[int] = field(
                                default=None,
                                metadata={
                                    "name": "FahrzeitprofilNummer",
                                    "type": "Element",
                                    "required": True,
                                },
                            )
                            fahrzeitprofilpunkte: Optional[
                                "Linienfahrplan.LinienDaten.Linie.RoutenDaten.Route.Fahrzeitprofile.Fahrzeitprofil.Fahrzeitprofilpunkte"
                            ] = field(
                                default=None,
                                metadata={
                                    "name": "Fahrzeitprofilpunkte",
                                    "type": "Element",
                                    "required": True,
                                },
                            )

                            @dataclass
                            class Fahrzeitprofilpunkte:
                                punkt: list[
                                    "Linienfahrplan.LinienDaten.Linie.RoutenDaten.Route.Fahrzeitprofile.Fahrzeitprofil.Fahrzeitprofilpunkte.Punkt"
                                ] = field(
                                    default_factory=list,
                                    metadata={
                                        "name": "Punkt",
                                        "type": "Element",
                                        "min_occurs": 1,
                                    },
                                )

                                @dataclass
                                class Punkt:
                                    lfd_nr: Optional[int] = field(
                                        default=None,
                                        metadata={
                                            "name": "LfdNr",
                                            "type": "Element",
                                            "required": True,
                                        },
                                    )
                                    streckenfahrzeit: Optional[int] = field(
                                        default=None,
                                        metadata={
                                            "name": "Streckenfahrzeit",
                                            "type": "Element",
                                            "required": True,
                                        },
                                    )
                                    wartezeit: Optional[int] = field(
                                        default=None,
                                        metadata={
                                            "name": "Wartezeit",
                                            "type": "Element",
                                            "required": True,
                                        },
                                    )

            @dataclass
            class Routenvarianten:
                routenvariante: list[
                    "Linienfahrplan.LinienDaten.Linie.Routenvarianten.Routenvariante"
                ] = field(
                    default_factory=list,
                    metadata={
                        "name": "Routenvariante",
                        "type": "Element",
                    },
                )

                @dataclass
                class Routenvariante:
                    lfd_nr: Optional[int] = field(
                        default=None,
                        metadata={
                            "name": "LfdNr",
                            "type": "Element",
                            "required": True,
                        },
                    )
                    lfd_nr_route: Optional[int] = field(
                        default=None,
                        metadata={
                            "name": "LfdNrRoute",
                            "type": "Element",
                            "required": True,
                        },
                    )
                    abweichender_auftraggeber: Optional[
                        "Linienfahrplan.LinienDaten.Linie.Routenvarianten.Routenvariante.AbweichenderAuftraggeber"
                    ] = field(
                        default=None,
                        metadata={
                            "name": "abweichenderAuftraggeber",
                            "type": "Element",
                        },
                    )
                    abweichende_veroeffentlichung: Optional[
                        "Linienfahrplan.LinienDaten.Linie.Routenvarianten.Routenvariante.AbweichendeVeroeffentlichung"
                    ] = field(
                        default=None,
                        metadata={
                            "name": "abweichendeVeroeffentlichung",
                            "type": "Element",
                        },
                    )

                    @dataclass
                    class AbweichenderAuftraggeber:
                        strecke: list[
                            "Linienfahrplan.LinienDaten.Linie.Routenvarianten.Routenvariante.AbweichenderAuftraggeber.Strecke"
                        ] = field(
                            default_factory=list,
                            metadata={
                                "name": "Strecke",
                                "type": "Element",
                                "min_occurs": 1,
                            },
                        )

                        @dataclass
                        class Strecke:
                            lfd_nr: Optional[int] = field(
                                default=None,
                                metadata={
                                    "name": "LfdNr",
                                    "type": "Element",
                                    "required": True,
                                },
                            )
                            auftraggeber: Optional[StreckeAuftraggeber] = field(
                                default=None,
                                metadata={
                                    "name": "Auftraggeber",
                                    "type": "Element",
                                    "required": True,
                                },
                            )

                    @dataclass
                    class AbweichendeVeroeffentlichung:
                        punkt: list[
                            "Linienfahrplan.LinienDaten.Linie.Routenvarianten.Routenvariante.AbweichendeVeroeffentlichung.Punkt"
                        ] = field(
                            default_factory=list,
                            metadata={
                                "name": "Punkt",
                                "type": "Element",
                                "min_occurs": 1,
                            },
                        )

                        @dataclass
                        class Punkt:
                            lfd_nr: Optional[int] = field(
                                default=None,
                                metadata={
                                    "name": "LfdNr",
                                    "type": "Element",
                                    "required": True,
                                },
                            )
                            veroeffentlicht: Optional[PunktVeroeffentlicht] = field(
                                default=None,
                                metadata={
                                    "type": "Element",
                                    "required": True,
                                },
                            )

    @dataclass
    class FahrtDaten:
        fahrt: list["Linienfahrplan.FahrtDaten.Fahrt"] = field(
            default_factory=list,
            metadata={
                "name": "Fahrt",
                "type": "Element",
            },
        )

        @dataclass
        class Fahrt:
            id: Optional[int] = field(
                default=None,
                metadata={
                    "name": "ID",
                    "type": "Element",
                    "required": True,
                },
            )
            linie: Optional[str] = field(
                default=None,
                metadata={
                    "name": "Linie",
                    "type": "Element",
                    "required": True,
                },
            )
            fahrgastrelevant: Optional[FahrtFahrgastrelevant] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "required": True,
                },
            )
            lfd_nr_routenvariante: Optional[int] = field(
                default=None,
                metadata={
                    "name": "LfdNrRoutenvariante",
                    "type": "Element",
                    "required": True,
                },
            )
            startzeit: Optional[int] = field(
                default=None,
                metadata={
                    "name": "Startzeit",
                    "type": "Element",
                    "required": True,
                },
            )
            fahrtart: Optional[str] = field(
                default=None,
                metadata={
                    "name": "Fahrtart",
                    "type": "Element",
                    "required": True,
                },
            )
            fahrzeitprofil: Optional[int] = field(
                default=None,
                metadata={
                    "name": "Fahrzeitprofil",
                    "type": "Element",
                    "required": True,
                },
            )
            fahrzeugtyp: Optional[str] = field(
                default=None,
                metadata={
                    "name": "Fahrzeugtyp",
                    "type": "Element",
                    "required": True,
                },
            )
            fremdunternehmer: Optional[int] = field(
                default=None,
                metadata={
                    "name": "Fremdunternehmer",
                    "type": "Element",
                    "required": True,
                },
            )
            auftraggeber: list[T41Auftraggeber] = field(
                default_factory=list,
                metadata={
                    "name": "Auftraggeber",
                    "type": "Element",
                    "max_occurs": 2,
                },
            )
            veroeffentlicht: list[T41Veroeffentlicht] = field(
                default_factory=list,
                metadata={
                    "type": "Element",
                    "max_occurs": 2,
                },
            )

    @dataclass
    class FahrzeugumlaufDaten:
        fahrzeugumlauf: list[
            "Linienfahrplan.FahrzeugumlaufDaten.Fahrzeugumlauf"
        ] = field(
            default_factory=list,
            metadata={
                "name": "Fahrzeugumlauf",
                "type": "Element",
            },
        )

        @dataclass
        class Fahrzeugumlauf:
            lfd_nr: Optional[int] = field(
                default=None,
                metadata={
                    "name": "LfdNr",
                    "type": "Element",
                    "required": True,
                },
            )
            betriebshof: Optional[int] = field(
                default=None,
                metadata={
                    "name": "Betriebshof",
                    "type": "Element",
                    "required": True,
                },
            )
            fahrzeugtyp: Optional[str] = field(
                default=None,
                metadata={
                    "name": "Fahrzeugtyp",
                    "type": "Element",
                    "required": True,
                },
            )
            umlaeufe: Optional[
                "Linienfahrplan.FahrzeugumlaufDaten.Fahrzeugumlauf.Umlaeufe"
            ] = field(
                default=None,
                metadata={
                    "name": "Umlaeufe",
                    "type": "Element",
                    "required": True,
                },
            )

            @dataclass
            class Umlaeufe:
                umlauf: list[
                    "Linienfahrplan.FahrzeugumlaufDaten.Fahrzeugumlauf.Umlaeufe.Umlauf"
                ] = field(
                    default_factory=list,
                    metadata={
                        "name": "Umlauf",
                        "type": "Element",
                        "min_occurs": 1,
                    },
                )

                @dataclass
                class Umlauf:
                    lfd_nr: Optional[int] = field(
                        default=None,
                        metadata={
                            "name": "LfdNr",
                            "type": "Element",
                            "required": True,
                        },
                    )
                    umlauf_id: Optional[int] = field(
                        default=None,
                        metadata={
                            "name": "UmlaufID",
                            "type": "Element",
                            "required": True,
                        },
                    )
                    umlaufbezeichnung: Optional[str] = field(
                        default=None,
                        metadata={
                            "name": "Umlaufbezeichnung",
                            "type": "Element",
                            "required": True,
                        },
                    )
                    kalenderdatum: Optional[str] = field(
                        default=None,
                        metadata={
                            "name": "Kalenderdatum",
                            "type": "Element",
                            "required": True,
                        },
                    )
                    umlaufteilgruppen: Optional[
                        "Linienfahrplan.FahrzeugumlaufDaten.Fahrzeugumlauf.Umlaeufe.Umlauf.Umlaufteilgruppen"
                    ] = field(
                        default=None,
                        metadata={
                            "name": "Umlaufteilgruppen",
                            "type": "Element",
                            "required": True,
                        },
                    )
                    gueltigkeiten: Optional[
                        "Linienfahrplan.FahrzeugumlaufDaten.Fahrzeugumlauf.Umlaeufe.Umlauf.Gueltigkeiten"
                    ] = field(
                        default=None,
                        metadata={
                            "name": "Gueltigkeiten",
                            "type": "Element",
                            "required": True,
                        },
                    )

                    @dataclass
                    class Umlaufteilgruppen:
                        umlaufteilgruppe: list[
                            "Linienfahrplan.FahrzeugumlaufDaten.Fahrzeugumlauf.Umlaeufe.Umlauf.Umlaufteilgruppen.Umlaufteilgruppe"
                        ] = field(
                            default_factory=list,
                            metadata={
                                "name": "Umlaufteilgruppe",
                                "type": "Element",
                                "min_occurs": 1,
                            },
                        )

                        @dataclass
                        class Umlaufteilgruppe:
                            lfd_nr: Optional[int] = field(
                                default=None,
                                metadata={
                                    "name": "LfdNr",
                                    "type": "Element",
                                    "required": True,
                                },
                            )
                            wagenfolgenummer: Optional[int] = field(
                                default=None,
                                metadata={
                                    "name": "Wagenfolgenummer",
                                    "type": "Element",
                                    "required": True,
                                },
                            )
                            linie: Optional[str] = field(
                                default=None,
                                metadata={
                                    "name": "Linie",
                                    "type": "Element",
                                    "required": True,
                                },
                            )
                            beginn: Optional[int] = field(
                                default=None,
                                metadata={
                                    "name": "Beginn",
                                    "type": "Element",
                                },
                            )
                            ende: Optional[int] = field(
                                default=None,
                                metadata={
                                    "name": "Ende",
                                    "type": "Element",
                                },
                            )
                            fahrzeugtyp: list[str] = field(
                                default_factory=list,
                                metadata={
                                    "name": "Fahrzeugtyp",
                                    "type": "Element",
                                    "max_occurs": 2,
                                },
                            )
                            fahrtreihenfolge: Optional[
                                "Linienfahrplan.FahrzeugumlaufDaten.Fahrzeugumlauf.Umlaeufe.Umlauf.Umlaufteilgruppen.Umlaufteilgruppe.Fahrtreihenfolge"
                            ] = field(
                                default=None,
                                metadata={
                                    "name": "Fahrtreihenfolge",
                                    "type": "Element",
                                },
                            )

                            @dataclass
                            class Fahrtreihenfolge:
                                fahrt: list[
                                    "Linienfahrplan.FahrzeugumlaufDaten.Fahrzeugumlauf.Umlaeufe.Umlauf.Umlaufteilgruppen.Umlaufteilgruppe.Fahrtreihenfolge.Fahrt"
                                ] = field(
                                    default_factory=list,
                                    metadata={
                                        "name": "Fahrt",
                                        "type": "Element",
                                        "min_occurs": 1,
                                    },
                                )

                                @dataclass
                                class Fahrt:
                                    lfd_nr: Optional[int] = field(
                                        default=None,
                                        metadata={
                                            "name": "LfdNr",
                                            "type": "Element",
                                            "required": True,
                                        },
                                    )
                                    fahrt_id: Optional[int] = field(
                                        default=None,
                                        metadata={
                                            "name": "FahrtID",
                                            "type": "Element",
                                            "required": True,
                                        },
                                    )

                    @dataclass
                    class Gueltigkeiten:
                        kalenderzeitraum: Optional[
                            "Linienfahrplan.FahrzeugumlaufDaten.Fahrzeugumlauf.Umlaeufe.Umlauf.Gueltigkeiten.Kalenderzeitraum"
                        ] = field(
                            default=None,
                            metadata={
                                "name": "Kalenderzeitraum",
                                "type": "Element",
                                "required": True,
                            },
                        )

                        @dataclass
                        class Kalenderzeitraum:
                            kalendertag: list[str] = field(
                                default_factory=list,
                                metadata={
                                    "name": "Kalendertag",
                                    "type": "Element",
                                    "min_occurs": 1,
                                },
                            )
