"""This file was generated by xsdata, v24.1, on 2024-01-24 17:07:06

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""
from dataclasses import dataclass, field
from decimal import Decimal
from enum import Enum

__NAMESPACE__ = "http://www.ivu.de/mb/intf/passengercount/remote/model/"


@dataclass
class AnzeigeText:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    value: str = field(
        default="",
        metadata={
            "required": True,
        },
    )


@dataclass
class Auftraggeber:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    value: None | int = field(default=None)


@dataclass
class Beginn:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    value: None | int = field(
        default=None,
        metadata={
            "required": True,
        },
    )


@dataclass
class Betriebshof:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    value: None | int = field(default=None)


@dataclass
class Build:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    value: str = field(default="")


@dataclass
class Datenversion:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    deployment_id: None | str = field(
        default=None,
        metadata={
            "name": "deploymentID",
            "type": "Element",
            "required": True,
        },
    )


@dataclass
class Ende:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    value: None | int = field(
        default=None,
        metadata={
            "required": True,
        },
    )


@dataclass
class Endpunkt:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    value: None | int = field(
        default=None,
        metadata={
            "required": True,
        },
    )


@dataclass
class EntfernungVomStart:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    value: None | int = field(default=None)


class FahrgastwechselValue(Enum):
    J = "J"
    N = "N"


@dataclass
class Fahrplanbuchname:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    value: str = field(
        default="",
        metadata={
            "required": True,
        },
    )


@dataclass
class FahrtId:
    class Meta:
        name = "FahrtID"
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    value: None | int = field(
        default=None,
        metadata={
            "required": True,
        },
    )


@dataclass
class Fahrtart:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    value: str = field(default="")


@dataclass
class FahrzeitprofilNummer:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    value: None | int = field(
        default=None,
        metadata={
            "required": True,
        },
    )


@dataclass
class Fahrzeugtyp:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    value: str = field(default="")


@dataclass
class Fremdunternehmer:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    value: None | int = field(default=None)


@dataclass
class Gebietskoerperschaft:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    content: list[object] = field(
        default_factory=list,
        metadata={
            "type": "Wildcard",
            "namespace": "##any",
            "mixed": True,
            "choices": (
                {
                    "name": "Kurzname",
                    "type": str,
                },
                {
                    "name": "Langname",
                    "type": str,
                },
            ),
        },
    )


@dataclass
class Haltestellenbereich:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    content: list[object] = field(
        default_factory=list,
        metadata={
            "type": "Wildcard",
            "namespace": "##any",
            "mixed": True,
            "choices": (
                {
                    "name": "Nummer",
                    "type": int,
                },
                {
                    "name": "Kurzname",
                    "type": str,
                },
                {
                    "name": "Fahrplanbuchname",
                    "type": str,
                },
            ),
        },
    )


class HauptrouteValue(Enum):
    J = "J"
    N = "N"


@dataclass
class Id:
    class Meta:
        name = "ID"
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    value: None | int = field(
        default=None,
        metadata={
            "required": True,
        },
    )


@dataclass
class Kalenderdatum:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    value: str = field(default="")


@dataclass
class Kalendertag:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    value: str = field(
        default="",
        metadata={
            "required": True,
        },
    )


@dataclass
class Kalenderzeitraum:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    kalendertag: list[str] = field(
        default_factory=list,
        metadata={
            "name": "Kalendertag",
            "type": "Element",
            "min_occurs": 1,
        },
    )


@dataclass
class Kurzname:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    value: str = field(
        default="",
        metadata={
            "required": True,
        },
    )


@dataclass
class Langname:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    value: str = field(
        default="",
        metadata={
            "required": True,
        },
    )


@dataclass
class LfdNr:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    value: None | int = field(
        default=None,
        metadata={
            "required": True,
        },
    )


@dataclass
class LfdNrRoute:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    value: None | int = field(
        default=None,
        metadata={
            "required": True,
        },
    )


@dataclass
class LfdNrRoutenvariante:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    value: None | int = field(
        default=None,
        metadata={
            "required": True,
        },
    )


class MeldungskategorieValue(Enum):
    VALUE_0 = 0
    VALUE_2 = 2


class MeldungsnummerValue(Enum):
    VALUE_0 = 0
    VALUE_18 = 18
    VALUE_5 = 5


class MeldungstextValue(Enum):
    ANFRAGE_WURDE_KORREKT_ABGEARBEITET = "Anfrage wurde korrekt abgearbeitet."
    KEINE_UML_UFE_VORHANDEN = "Keine Umläufe vorhanden."
    KEINE_G_LTIGE_LINIE = "Keine gültige Linie."


class NameValue(Enum):
    BETRIEBSBEREICH = "Betriebsbereich"
    KEINE_ANZEIGEDATEN = "KeineAnzeigedaten"
    KEINE_GUELTIGKEITEN = "KeineGueltigkeiten"
    LINIE = "Linie"
    MELDUNGSKATEGORIE = "Meldungskategorie"
    STICHTAG = "Stichtag"


class NetzpunkttypValue(Enum):
    APKT = "APkt"
    BPUNKT = "BPunkt"
    EPKT = "EPkt"
    GPKT = "GPkt"
    HST = "Hst"


@dataclass
class Nummer:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    value: None | int = field(
        default=None,
        metadata={
            "required": True,
        },
    )


class ReleaseValue(Enum):
    VALUE_21_2_0_20220203_0833_898844 = "21.2.0-20220203-0833-898844"


class ReturnCodeValue(Enum):
    VALUE_0 = 0
    VALUE_1 = 1


class RichtungValue(Enum):
    VALUE_0 = 0
    VALUE_1 = 1
    VALUE_2 = 2


@dataclass
class Startpunkt:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    value: None | int = field(
        default=None,
        metadata={
            "required": True,
        },
    )


@dataclass
class Startzeit:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    value: None | int = field(
        default=None,
        metadata={
            "required": True,
        },
    )


@dataclass
class Startzeitpunkt:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    value: str = field(
        default="",
        metadata={
            "required": True,
        },
    )


@dataclass
class StreckenId:
    class Meta:
        name = "StreckenID"
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    value: None | int = field(
        default=None,
        metadata={
            "required": True,
        },
    )


@dataclass
class Streckenfahrzeit:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    value: None | int = field(
        default=None,
        metadata={
            "required": True,
        },
    )


@dataclass
class Streckenlaenge:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    value: None | int = field(
        default=None,
        metadata={
            "required": True,
        },
    )


@dataclass
class UmlaufId:
    class Meta:
        name = "UmlaufID"
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    value: None | int = field(
        default=None,
        metadata={
            "required": True,
        },
    )


@dataclass
class Umlaufbezeichnung:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    value: str = field(
        default="",
        metadata={
            "required": True,
        },
    )


@dataclass
class Version:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    value: None | Decimal = field(default=None)


@dataclass
class Wagenfolgenummer:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    value: None | int = field(
        default=None,
        metadata={
            "required": True,
        },
    )


@dataclass
class Wartezeit:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    value: None | int = field(default=None)


@dataclass
class Wert:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    value: str = field(
        default="",
        metadata={
            "required": True,
        },
    )


@dataclass
class Xkoordinate:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    value: None | int = field(
        default=None,
        metadata={
            "required": True,
        },
    )


@dataclass
class Ykoordinate:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    value: None | int = field(
        default=None,
        metadata={
            "required": True,
        },
    )


@dataclass
class Zielanzeige:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    content: list[object] = field(
        default_factory=list,
        metadata={
            "type": "Wildcard",
            "namespace": "##any",
            "mixed": True,
            "choices": (
                {
                    "name": "Nummer",
                    "type": int,
                },
                {
                    "name": "AnzeigeText",
                    "type": str,
                },
            ),
        },
    )


@dataclass
class DeploymentId:
    class Meta:
        name = "deploymentID"
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    value: str = field(default="")


@dataclass
class ExterneRoutennummer:
    class Meta:
        name = "externeRoutennummer"
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    value: None | int = field(
        default=None,
        metadata={
            "required": True,
        },
    )


class FahrgastrelevantValue(Enum):
    J = "J"
    N = "N"


class MitFahrgastwechselValue(Enum):
    J = "J"
    N = "N"


class VeroeffentlichtValue(Enum):
    J = "J"
    N = "N"


@dataclass
class ZugeordneteBetriebshoefe:
    class Meta:
        name = "zugeordneteBetriebshoefe"
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    betriebshof: list[int] = field(
        default_factory=list,
        metadata={
            "name": "Betriebshof",
            "type": "Element",
        },
    )


@dataclass
class Fahrgastwechsel:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    value: None | FahrgastwechselValue = field(default=None)


@dataclass
class Gebietskoerperschaften:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    gebietskoerperschaft: list[Gebietskoerperschaft] = field(
        default_factory=list,
        metadata={
            "name": "Gebietskoerperschaft",
            "type": "Element",
        },
    )


@dataclass
class Gueltigkeiten:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    kalenderzeitraum: None | Kalenderzeitraum = field(
        default=None,
        metadata={
            "name": "Kalenderzeitraum",
            "type": "Element",
            "required": True,
        },
    )


@dataclass
class Haltestellenbereiche:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    haltestellenbereich: list[Haltestellenbereich] = field(
        default_factory=list,
        metadata={
            "name": "Haltestellenbereich",
            "type": "Element",
        },
    )


@dataclass
class Hauptroute:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    value: None | HauptrouteValue = field(default=None)


@dataclass
class Meldung:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    meldungskategorie: None | MeldungskategorieValue = field(
        default=None,
        metadata={
            "name": "Meldungskategorie",
            "type": "Element",
            "required": True,
        },
    )
    meldungsnummer: None | MeldungsnummerValue = field(
        default=None,
        metadata={
            "name": "Meldungsnummer",
            "type": "Element",
            "required": True,
        },
    )
    meldungstext: None | MeldungstextValue = field(
        default=None,
        metadata={
            "name": "Meldungstext",
            "type": "Element",
            "required": True,
        },
    )


@dataclass
class Meldungskategorie:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    value: None | MeldungskategorieValue = field(default=None)


@dataclass
class Meldungsnummer:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    value: None | MeldungsnummerValue = field(default=None)


@dataclass
class Meldungstext:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    value: None | MeldungstextValue = field(default=None)


@dataclass
class Name:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    value: None | NameValue = field(default=None)


@dataclass
class Netzpunkttyp:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    value: None | NetzpunkttypValue = field(default=None)


@dataclass
class Parameter:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    name: None | NameValue = field(
        default=None,
        metadata={
            "name": "Name",
            "type": "Element",
            "required": True,
        },
    )
    wert: None | str = field(
        default=None,
        metadata={
            "name": "Wert",
            "type": "Element",
            "required": True,
        },
    )


@dataclass
class Release:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    value: None | ReleaseValue = field(default=None)


@dataclass
class ReturnCode:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    value: None | ReturnCodeValue = field(default=None)


@dataclass
class Richtung:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    value: None | RichtungValue = field(default=None)


@dataclass
class Schnittstellenversion:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    version: None | Decimal = field(
        default=None,
        metadata={
            "name": "Version",
            "type": "Element",
            "required": True,
        },
    )
    release: None | ReleaseValue = field(
        default=None,
        metadata={
            "name": "Release",
            "type": "Element",
            "required": True,
        },
    )
    build: None | str = field(
        default=None,
        metadata={
            "name": "Build",
            "type": "Element",
            "required": True,
        },
    )


@dataclass
class Zielanzeigen:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    zielanzeige: list[Zielanzeige] = field(
        default_factory=list,
        metadata={
            "name": "Zielanzeige",
            "type": "Element",
        },
    )


@dataclass
class Fahrgastrelevant:
    class Meta:
        name = "fahrgastrelevant"
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    value: None | FahrgastrelevantValue = field(default=None)


@dataclass
class MitFahrgastwechsel:
    class Meta:
        name = "mitFahrgastwechsel"
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    value: None | MitFahrgastwechselValue = field(default=None)


@dataclass
class Veroeffentlicht:
    class Meta:
        name = "veroeffentlicht"
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    value: None | VeroeffentlichtValue = field(default=None)


@dataclass
class GenerierungsParameter:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    parameter: list[Parameter] = field(
        default_factory=list,
        metadata={
            "name": "Parameter",
            "type": "Element",
            "min_occurs": 1,
        },
    )


@dataclass
class Meldungsliste:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    meldung: None | Meldung = field(
        default=None,
        metadata={
            "name": "Meldung",
            "type": "Element",
            "required": True,
        },
    )


@dataclass
class Netzpunkt:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    content: list[object] = field(
        default_factory=list,
        metadata={
            "type": "Wildcard",
            "namespace": "##any",
            "mixed": True,
            "choices": (
                {
                    "name": "Nummer",
                    "type": int,
                },
                {
                    "name": "Kurzname",
                    "type": str,
                },
                {
                    "name": "Langname",
                    "type": str,
                },
                {
                    "name": "Netzpunkttyp",
                    "type": NetzpunkttypValue,
                },
                {
                    "name": "Xkoordinate",
                    "type": int,
                },
                {
                    "name": "Ykoordinate",
                    "type": int,
                },
                {
                    "name": "Haltestellenbereich",
                    "type": Haltestellenbereich,
                },
                {
                    "name": "mitFahrgastwechsel",
                    "type": MitFahrgastwechselValue,
                },
                {
                    "name": "Gebietskoerperschaften",
                    "type": Gebietskoerperschaften,
                },
            ),
        },
    )


@dataclass
class Ergebnis:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    return_code: None | ReturnCodeValue = field(
        default=None,
        metadata={
            "name": "ReturnCode",
            "type": "Element",
            "required": True,
        },
    )
    meldungsliste: None | Meldungsliste = field(
        default=None,
        metadata={
            "name": "Meldungsliste",
            "type": "Element",
            "required": True,
        },
    )


@dataclass
class Netzpunkte:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    netzpunkt: list[Netzpunkt] = field(
        default_factory=list,
        metadata={
            "name": "Netzpunkt",
            "type": "Element",
        },
    )


@dataclass
class Punkt:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    lfd_nr: None | int = field(
        default=None,
        metadata={
            "name": "LfdNr",
            "type": "Element",
            "required": True,
        },
    )
    netzpunkt: None | Netzpunkt = field(
        default=None,
        metadata={
            "name": "Netzpunkt",
            "type": "Element",
        },
    )
    fahrgastwechsel: None | FahrgastwechselValue = field(
        default=None,
        metadata={
            "name": "Fahrgastwechsel",
            "type": "Element",
        },
    )
    veroeffentlicht: list[VeroeffentlichtValue] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "max_occurs": 2,
        },
    )
    zielanzeige: None | Zielanzeige = field(
        default=None,
        metadata={
            "name": "Zielanzeige",
            "type": "Element",
        },
    )
    streckenfahrzeit: None | int = field(
        default=None,
        metadata={
            "name": "Streckenfahrzeit",
            "type": "Element",
        },
    )
    wartezeit: None | int = field(
        default=None,
        metadata={
            "name": "Wartezeit",
            "type": "Element",
        },
    )


@dataclass
class Zwischenpunkt:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    netzpunkt: None | Netzpunkt = field(
        default=None,
        metadata={
            "name": "Netzpunkt",
            "type": "Element",
            "required": True,
        },
    )
    entfernung_vom_start: None | int = field(
        default=None,
        metadata={
            "name": "EntfernungVomStart",
            "type": "Element",
            "required": True,
        },
    )


@dataclass
class Fahrzeitprofilpunkte:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    punkt: list[Punkt] = field(
        default_factory=list,
        metadata={
            "name": "Punkt",
            "type": "Element",
            "min_occurs": 1,
        },
    )


@dataclass
class Generierung:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    startzeitpunkt: None | str = field(
        default=None,
        metadata={
            "name": "Startzeitpunkt",
            "type": "Element",
            "required": True,
        },
    )
    schnittstellenversion: None | Schnittstellenversion = field(
        default=None,
        metadata={
            "name": "Schnittstellenversion",
            "type": "Element",
            "required": True,
        },
    )
    datenversion: None | Datenversion = field(
        default=None,
        metadata={
            "name": "Datenversion",
            "type": "Element",
            "required": True,
        },
    )
    ergebnis: None | Ergebnis = field(
        default=None,
        metadata={
            "name": "Ergebnis",
            "type": "Element",
            "required": True,
        },
    )
    generierungs_parameter: None | GenerierungsParameter = field(
        default=None,
        metadata={
            "name": "GenerierungsParameter",
            "type": "Element",
            "required": True,
        },
    )


@dataclass
class Punktfolge:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    punkt: list[Punkt] = field(
        default_factory=list,
        metadata={
            "name": "Punkt",
            "type": "Element",
            "min_occurs": 1,
        },
    )


@dataclass
class Zwischenpunkte:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    zwischenpunkt: None | Zwischenpunkt = field(
        default=None,
        metadata={
            "name": "Zwischenpunkt",
            "type": "Element",
        },
    )


@dataclass
class AbweichendeVeroeffentlichung:
    class Meta:
        name = "abweichendeVeroeffentlichung"
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    punkt: list[Punkt] = field(
        default_factory=list,
        metadata={
            "name": "Punkt",
            "type": "Element",
            "min_occurs": 1,
        },
    )


@dataclass
class Fahrzeitprofil:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    content: list[object] = field(
        default_factory=list,
        metadata={
            "type": "Wildcard",
            "namespace": "##any",
            "mixed": True,
            "choices": (
                {
                    "name": "FahrzeitprofilNummer",
                    "type": int,
                },
                {
                    "name": "Fahrzeitprofilpunkte",
                    "type": Fahrzeitprofilpunkte,
                },
            ),
        },
    )


@dataclass
class Strecke:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    id: None | int = field(
        default=None,
        metadata={
            "name": "ID",
            "type": "Element",
        },
    )
    startpunkt: None | int = field(
        default=None,
        metadata={
            "name": "Startpunkt",
            "type": "Element",
        },
    )
    endpunkt: None | int = field(
        default=None,
        metadata={
            "name": "Endpunkt",
            "type": "Element",
        },
    )
    streckenlaenge: None | int = field(
        default=None,
        metadata={
            "name": "Streckenlaenge",
            "type": "Element",
        },
    )
    zwischenpunkte: None | Zwischenpunkte = field(
        default=None,
        metadata={
            "name": "Zwischenpunkte",
            "type": "Element",
        },
    )
    lfd_nr: None | int = field(
        default=None,
        metadata={
            "name": "LfdNr",
            "type": "Element",
        },
    )
    strecken_id: None | int = field(
        default=None,
        metadata={
            "name": "StreckenID",
            "type": "Element",
        },
    )
    auftraggeber: list[int] = field(
        default_factory=list,
        metadata={
            "name": "Auftraggeber",
            "type": "Element",
            "min_occurs": 1,
            "max_occurs": 2,
            "sequence": 1,
        },
    )


@dataclass
class Fahrzeitprofile:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    fahrzeitprofil: list[Fahrzeitprofil] = field(
        default_factory=list,
        metadata={
            "name": "Fahrzeitprofil",
            "type": "Element",
            "min_occurs": 1,
        },
    )


@dataclass
class Strecken:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    strecke: list[Strecke] = field(
        default_factory=list,
        metadata={
            "name": "Strecke",
            "type": "Element",
        },
    )


@dataclass
class Streckenfolge:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    strecke: list[Strecke] = field(
        default_factory=list,
        metadata={
            "name": "Strecke",
            "type": "Element",
            "min_occurs": 1,
        },
    )


@dataclass
class AbweichenderAuftraggeber:
    class Meta:
        name = "abweichenderAuftraggeber"
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    strecke: list[Strecke] = field(
        default_factory=list,
        metadata={
            "name": "Strecke",
            "type": "Element",
            "min_occurs": 1,
        },
    )


@dataclass
class Route:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    lfd_nr: None | int = field(
        default=None,
        metadata={
            "name": "LfdNr",
            "type": "Element",
            "required": True,
        },
    )
    externe_routennummer: None | int = field(
        default=None,
        metadata={
            "name": "externeRoutennummer",
            "type": "Element",
            "required": True,
        },
    )
    richtung: None | RichtungValue = field(
        default=None,
        metadata={
            "name": "Richtung",
            "type": "Element",
            "required": True,
        },
    )
    hauptroute: None | HauptrouteValue = field(
        default=None,
        metadata={
            "name": "Hauptroute",
            "type": "Element",
            "required": True,
        },
    )
    zielanzeigen: None | Zielanzeigen = field(
        default=None,
        metadata={
            "name": "Zielanzeigen",
            "type": "Element",
            "required": True,
        },
    )
    streckenfolge: None | Streckenfolge = field(
        default=None,
        metadata={
            "name": "Streckenfolge",
            "type": "Element",
            "required": True,
        },
    )
    punktfolge: None | Punktfolge = field(
        default=None,
        metadata={
            "name": "Punktfolge",
            "type": "Element",
            "required": True,
        },
    )
    fahrzeitprofile: None | Fahrzeitprofile = field(
        default=None,
        metadata={
            "name": "Fahrzeitprofile",
            "type": "Element",
            "required": True,
        },
    )


@dataclass
class Routenvariante:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    lfd_nr: None | int = field(
        default=None,
        metadata={
            "name": "LfdNr",
            "type": "Element",
            "required": True,
        },
    )
    lfd_nr_route: None | int = field(
        default=None,
        metadata={
            "name": "LfdNrRoute",
            "type": "Element",
            "required": True,
        },
    )
    abweichender_auftraggeber: None | AbweichenderAuftraggeber = field(
        default=None,
        metadata={
            "name": "abweichenderAuftraggeber",
            "type": "Element",
        },
    )
    abweichende_veroeffentlichung: None | AbweichendeVeroeffentlichung = field(
        default=None,
        metadata={
            "name": "abweichendeVeroeffentlichung",
            "type": "Element",
        },
    )


@dataclass
class StreckennetzDaten:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    haltestellenbereiche: None | Haltestellenbereiche = field(
        default=None,
        metadata={
            "name": "Haltestellenbereiche",
            "type": "Element",
            "required": True,
        },
    )
    netzpunkte: None | Netzpunkte = field(
        default=None,
        metadata={
            "name": "Netzpunkte",
            "type": "Element",
            "required": True,
        },
    )
    gebietskoerperschaften: None | Gebietskoerperschaften = field(
        default=None,
        metadata={
            "name": "Gebietskoerperschaften",
            "type": "Element",
            "required": True,
        },
    )
    strecken: None | Strecken = field(
        default=None,
        metadata={
            "name": "Strecken",
            "type": "Element",
            "required": True,
        },
    )


@dataclass
class RoutenDaten:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    route: list[Route] = field(
        default_factory=list,
        metadata={
            "name": "Route",
            "type": "Element",
        },
    )


@dataclass
class Routenvarianten:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    routenvariante: list[Routenvariante] = field(
        default_factory=list,
        metadata={
            "name": "Routenvariante",
            "type": "Element",
        },
    )


@dataclass
class Linie:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    content: list[object] = field(
        default_factory=list,
        metadata={
            "type": "Wildcard",
            "namespace": "##any",
            "mixed": True,
            "choices": (
                {
                    "name": "Kurzname",
                    "type": str,
                },
                {
                    "name": "zugeordneteBetriebshoefe",
                    "type": ZugeordneteBetriebshoefe,
                },
                {
                    "name": "RoutenDaten",
                    "type": RoutenDaten,
                },
                {
                    "name": "Routenvarianten",
                    "type": Routenvarianten,
                },
            ),
        },
    )


@dataclass
class Fahrt:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    id: None | int = field(
        default=None,
        metadata={
            "name": "ID",
            "type": "Element",
        },
    )
    linie: None | Linie = field(
        default=None,
        metadata={
            "name": "Linie",
            "type": "Element",
        },
    )
    fahrgastrelevant: None | FahrgastrelevantValue = field(
        default=None,
        metadata={
            "type": "Element",
        },
    )
    lfd_nr_routenvariante: None | int = field(
        default=None,
        metadata={
            "name": "LfdNrRoutenvariante",
            "type": "Element",
        },
    )
    startzeit: None | int = field(
        default=None,
        metadata={
            "name": "Startzeit",
            "type": "Element",
        },
    )
    fahrtart: None | str = field(
        default=None,
        metadata={
            "name": "Fahrtart",
            "type": "Element",
        },
    )
    fahrzeitprofil: None | Fahrzeitprofil = field(
        default=None,
        metadata={
            "name": "Fahrzeitprofil",
            "type": "Element",
        },
    )
    fahrzeugtyp: None | str = field(
        default=None,
        metadata={
            "name": "Fahrzeugtyp",
            "type": "Element",
        },
    )
    fremdunternehmer: None | int = field(
        default=None,
        metadata={
            "name": "Fremdunternehmer",
            "type": "Element",
        },
    )
    auftraggeber: list[int] = field(
        default_factory=list,
        metadata={
            "name": "Auftraggeber",
            "type": "Element",
            "max_occurs": 2,
        },
    )
    veroeffentlicht: list[VeroeffentlichtValue] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "max_occurs": 2,
        },
    )
    lfd_nr: None | int = field(
        default=None,
        metadata={
            "name": "LfdNr",
            "type": "Element",
        },
    )
    fahrt_id: None | int = field(
        default=None,
        metadata={
            "name": "FahrtID",
            "type": "Element",
        },
    )


@dataclass
class LinienDaten:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    linie: None | Linie = field(
        default=None,
        metadata={
            "name": "Linie",
            "type": "Element",
            "required": True,
        },
    )


@dataclass
class FahrtDaten:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    fahrt: list[Fahrt] = field(
        default_factory=list,
        metadata={
            "name": "Fahrt",
            "type": "Element",
        },
    )


@dataclass
class Fahrtreihenfolge:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    fahrt: list[Fahrt] = field(
        default_factory=list,
        metadata={
            "name": "Fahrt",
            "type": "Element",
            "min_occurs": 1,
        },
    )


@dataclass
class Umlaufteilgruppe:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    lfd_nr: None | int = field(
        default=None,
        metadata={
            "name": "LfdNr",
            "type": "Element",
            "required": True,
        },
    )
    wagenfolgenummer: None | int = field(
        default=None,
        metadata={
            "name": "Wagenfolgenummer",
            "type": "Element",
            "required": True,
        },
    )
    linie: None | Linie = field(
        default=None,
        metadata={
            "name": "Linie",
            "type": "Element",
            "required": True,
        },
    )
    beginn: None | int = field(
        default=None,
        metadata={
            "name": "Beginn",
            "type": "Element",
        },
    )
    ende: None | int = field(
        default=None,
        metadata={
            "name": "Ende",
            "type": "Element",
        },
    )
    fahrzeugtyp: list[str] = field(
        default_factory=list,
        metadata={
            "name": "Fahrzeugtyp",
            "type": "Element",
            "max_occurs": 2,
        },
    )
    fahrtreihenfolge: None | Fahrtreihenfolge = field(
        default=None,
        metadata={
            "name": "Fahrtreihenfolge",
            "type": "Element",
        },
    )


@dataclass
class Umlaufteilgruppen:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    umlaufteilgruppe: list[Umlaufteilgruppe] = field(
        default_factory=list,
        metadata={
            "name": "Umlaufteilgruppe",
            "type": "Element",
            "min_occurs": 1,
        },
    )


@dataclass
class Umlauf:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    lfd_nr: None | int = field(
        default=None,
        metadata={
            "name": "LfdNr",
            "type": "Element",
            "required": True,
        },
    )
    umlauf_id: None | int = field(
        default=None,
        metadata={
            "name": "UmlaufID",
            "type": "Element",
            "required": True,
        },
    )
    umlaufbezeichnung: None | str = field(
        default=None,
        metadata={
            "name": "Umlaufbezeichnung",
            "type": "Element",
            "required": True,
        },
    )
    kalenderdatum: None | str = field(
        default=None,
        metadata={
            "name": "Kalenderdatum",
            "type": "Element",
            "required": True,
        },
    )
    umlaufteilgruppen: None | Umlaufteilgruppen = field(
        default=None,
        metadata={
            "name": "Umlaufteilgruppen",
            "type": "Element",
            "required": True,
        },
    )
    gueltigkeiten: None | Gueltigkeiten = field(
        default=None,
        metadata={
            "name": "Gueltigkeiten",
            "type": "Element",
            "required": True,
        },
    )


@dataclass
class Umlaeufe:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    umlauf: list[Umlauf] = field(
        default_factory=list,
        metadata={
            "name": "Umlauf",
            "type": "Element",
            "min_occurs": 1,
        },
    )


@dataclass
class Fahrzeugumlauf:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    lfd_nr: None | int = field(
        default=None,
        metadata={
            "name": "LfdNr",
            "type": "Element",
            "required": True,
        },
    )
    betriebshof: None | int = field(
        default=None,
        metadata={
            "name": "Betriebshof",
            "type": "Element",
            "required": True,
        },
    )
    fahrzeugtyp: None | str = field(
        default=None,
        metadata={
            "name": "Fahrzeugtyp",
            "type": "Element",
            "required": True,
        },
    )
    umlaeufe: None | Umlaeufe = field(
        default=None,
        metadata={
            "name": "Umlaeufe",
            "type": "Element",
            "required": True,
        },
    )


@dataclass
class FahrzeugumlaufDaten:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    fahrzeugumlauf: list[Fahrzeugumlauf] = field(
        default_factory=list,
        metadata={
            "name": "Fahrzeugumlauf",
            "type": "Element",
        },
    )


@dataclass
class Linienfahrplan:
    class Meta:
        namespace = "http://www.ivu.de/mb/intf/passengercount/remote/model/"

    generierung: None | Generierung = field(
        default=None,
        metadata={
            "name": "Generierung",
            "type": "Element",
            "required": True,
        },
    )
    streckennetz_daten: None | StreckennetzDaten = field(
        default=None,
        metadata={
            "name": "StreckennetzDaten",
            "type": "Element",
        },
    )
    linien_daten: None | LinienDaten = field(
        default=None,
        metadata={
            "name": "LinienDaten",
            "type": "Element",
        },
    )
    fahrt_daten: None | FahrtDaten = field(
        default=None,
        metadata={
            "name": "FahrtDaten",
            "type": "Element",
        },
    )
    fahrzeugumlauf_daten: None | FahrzeugumlaufDaten = field(
        default=None,
        metadata={
            "name": "FahrzeugumlaufDaten",
            "type": "Element",
        },
    )
