"""This file was originally generated by xsdata, v24.1, on 2024-01-29 15:42:25
+ modified

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""
from dataclasses import dataclass, field
from typing import Optional


@dataclass(kw_only=True)
class BasisVerGueltigkeit:
    class Meta:
        name = "BASIS_VER_GUELTIGKEIT"

    ver_gueltigkeit: int = field(
        metadata={
            "name": "VER_GUELTIGKEIT",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 99999999,
        }
    )
    basis_version: int = field(
        metadata={
            "name": "BASIS_VERSION",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 999999999,
        }
    )


@dataclass(kw_only=True)
class Firmenkalender:
    class Meta:
        name = "FIRMENKALENDER"

    basis_version: int = field(
        metadata={
            "name": "BASIS_VERSION",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 999999999,
        }
    )
    betriebstag: int = field(
        metadata={
            "name": "BETRIEBSTAG",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 99999999,
        }
    )

    tagesart_nr: int = field(
        metadata={
            "name": "TAGESART_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 999,
        }
    )


@dataclass(kw_only=True)
class LidVerlauf:
    class Meta:
        name = "LID_VERLAUF"

    basis_version: int = field(
        metadata={
            "name": "BASIS_VERSION",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 999999999,
        }
    )
    li_lfd_nr: int = field(
        metadata={
            "name": "LI_LFD_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 999,
        }
    )
    li_nr: int = field(
        metadata={
            "name": "LI_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 999999,
        }
    )
    str_li_var: str = field(
        metadata={
            "name": "STR_LI_VAR",
            "type": "Element",
            "required": True,
            "max_length": 6,
        }
    )
    onr_typ_nr: int = field(
        metadata={
            "name": "ONR_TYP_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 2,
        }
    )
    ort_nr: int = field(
        metadata={
            "name": "ORT_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 999999,
        }
    )

    produktiv: Optional[bool] = field(
        default=None,
        metadata={
            "name": "PRODUKTIV",
            "type": "Element",
            "nillable": True,
        },
    )


@dataclass(kw_only=True)
class OrtHztf:
    class Meta:
        name = "ORT_HZTF"

    basis_version: int = field(
        metadata={
            "name": "BASIS_VERSION",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 999999999,
        }
    )
    fgr_nr: int = field(
        metadata={
            "name": "FGR_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 999999999,
        }
    )
    onr_typ_nr: int = field(
        metadata={
            "name": "ONR_TYP_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 2,
        }
    )
    ort_nr: int = field(
        metadata={
            "name": "ORT_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 999999,
        }
    )
    hp_hzt: int = field(
        metadata={
            "name": "HP_HZT",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 65532,
        }
    )


@dataclass(kw_only=True)
class RecFrtHzt:
    class Meta:
        name = "REC_FRT_HZT"

    basis_version: int = field(
        metadata={
            "name": "BASIS_VERSION",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 999999999,
        }
    )
    frt_fid: int = field(
        metadata={
            "name": "FRT_FID",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 9999999999,
        }
    )
    onr_typ_nr: int = field(
        metadata={
            "name": "ONR_TYP_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 2,
        }
    )
    ort_nr: int = field(
        metadata={
            "name": "ORT_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": 0,
            "max_inclusive": 999999,
        }
    )
    frt_hzt_zeit: int = field(
        metadata={
            "name": "FRT_HZT_ZEIT",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 65532,
        }
    )


@dataclass(kw_only=True)
class SelFztFeld:
    class Meta:
        name = "SEL_FZT_FELD"

    basis_version: int = field(
        metadata={
            "name": "BASIS_VERSION",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 999999999,
        }
    )
    bereich_nr: int = field(
        metadata={
            "name": "BEREICH_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": 0,
            "max_inclusive": 252,
        }
    )
    fgr_nr: int = field(
        metadata={
            "name": "FGR_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 999999999,
        }
    )
    onr_typ_nr: int = field(
        metadata={
            "name": "ONR_TYP_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 2,
        }
    )
    ort_nr: int = field(
        metadata={
            "name": "ORT_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 999999,
        }
    )
    sel_ziel: int = field(
        metadata={
            "name": "SEL_ZIEL",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 999999,
        }
    )
    sel_ziel_typ: int = field(
        metadata={
            "name": "SEL_ZIEL_TYP",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 2,
        }
    )
    sel_fzt: int = field(
        metadata={
            "name": "SEL_FZT",
            "type": "Element",
            "required": True,
            "min_inclusive": 0,
            "max_inclusive": 65532,
        }
    )


@dataclass(kw_only=True)
class UebFzt:
    class Meta:
        name = "UEB_FZT"

    basis_version: int = field(
        metadata={
            "name": "BASIS_VERSION",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 999999999,
        }
    )
    bereich_nr: int = field(
        metadata={
            "name": "BEREICH_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": 0,
            "max_inclusive": 252,
        }
    )
    fgr_nr: int = field(
        metadata={
            "name": "FGR_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 999999999,
        }
    )
    onr_typ_nr: int = field(
        metadata={
            "name": "ONR_TYP_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 2,
        }
    )
    ort_nr: int = field(
        metadata={
            "name": "ORT_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 999999,
        }
    )
    ueb_ziel_typ: int = field(
        metadata={
            "name": "UEB_ZIEL_TYP",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 2,
        }
    )
    ueb_ziel: int = field(
        metadata={
            "name": "UEB_ZIEL",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 999999,
        }
    )
    ueb_fahrzeit: int = field(
        metadata={
            "name": "UEB_FAHRZEIT",
            "type": "Element",
            "required": True,
            "min_inclusive": 0,
            "max_inclusive": 65532,
        }
    )


@dataclass(kw_only=True)
class RecFrt:
    class Meta:
        name = "REC_FRT"

    basis_version: int = field(
        metadata={
            "name": "BASIS_VERSION",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 999999999,
        }
    )
    frt_fid: int = field(
        metadata={
            "name": "FRT_FID",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 9999999999,
        }
    )
    frt_start: int = field(
        metadata={
            "name": "FRT_START",
            "type": "Element",
            "required": True,
            "min_inclusive": 0,
            "max_inclusive": 129600,
        }
    )
    li_nr: int = field(
        metadata={
            "name": "LI_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 999999,
        }
    )
    tagesart_nr: int = field(
        metadata={
            "name": "TAGESART_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 999,
        }
    )

    fahrtart_nr: int = field(
        metadata={
            "name": "FAHRTART_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 4,
        }
    )
    fgr_nr: int = field(
        metadata={
            "name": "FGR_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    str_li_var: str = field(
        metadata={
            "name": "STR_LI_VAR",
            "type": "Element",
            "required": True,
            "max_length": 6,
        }
    )
    um_uid: int = field(
        metadata={
            "name": "UM_UID",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )

    rec_frt_hzt: list[RecFrtHzt] = field(
        default_factory=list,
        metadata={
            "name": "REC_FRT_HZT",
            "type": "Element",
        },
    )


@dataclass(kw_only=True)
class RecOrt:
    class Meta:
        name = "REC_ORT"

    basis_version: int = field(
        metadata={
            "name": "BASIS_VERSION",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 999999999,
        }
    )
    onr_typ_nr: int = field(
        metadata={
            "name": "ONR_TYP_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 7,
        }
    )
    ort_nr: int = field(
        metadata={
            "name": "ORT_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 999999,
        }
    )
    ort_name: str = field(
        metadata={
            "name": "ORT_NAME",
            "type": "Element",
            "required": True,
            "max_length": 40,
        }
    )

    # lid_verlauf: list[LidVerlauf] = field(
    #     default_factory=list,
    #     metadata={
    #         "name": "LID_VERLAUF",
    #         "type": "Element",
    #     },
    # )
    # ort_hztf: list[OrtHztf] = field(
    #     default_factory=list,
    #     metadata={
    #         "name": "ORT_HZTF",
    #         "type": "Element",
    #     },
    # )


@dataclass(kw_only=True)
class RecSel:
    class Meta:
        name = "REC_SEL"

    basis_version: int = field(
        metadata={
            "name": "BASIS_VERSION",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 999999999,
        }
    )
    bereich_nr: int = field(
        metadata={
            "name": "BEREICH_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": 0,
            "max_inclusive": 252,
        }
    )
    onr_typ_nr: int = field(
        metadata={
            "name": "ONR_TYP_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 2,
        }
    )
    ort_nr: int = field(
        metadata={
            "name": "ORT_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -1,
            "max_inclusive": 999999,
        }
    )
    sel_ziel: int = field(
        metadata={
            "name": "SEL_ZIEL",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 999999,
        }
    )
    sel_ziel_typ: int = field(
        metadata={
            "name": "SEL_ZIEL_TYP",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 2,
        }
    )
    sel_laenge: Optional[int] = field(
        metadata={
            "name": "SEL_LAENGE",
            "type": "Element",
            "min_inclusive": 1,
            "max_inclusive": 81890,
            "nillable": True,
        }
    )

    sel_fzt_feld: list[SelFztFeld] = field(
        default_factory=list,
        metadata={
            "name": "SEL_FZT_FELD",
            "type": "Element",
        },
    )


@dataclass(kw_only=True)
class RecUeb:
    class Meta:
        name = "REC_UEB"

    basis_version: int = field(
        metadata={
            "name": "BASIS_VERSION",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 999999999,
        }
    )
    bereich_nr: int = field(
        metadata={
            "name": "BEREICH_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": 0,
            "max_inclusive": 252,
        }
    )
    onr_typ_nr: int = field(
        metadata={
            "name": "ONR_TYP_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 2,
        }
    )
    ort_nr: int = field(
        metadata={
            "name": "ORT_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 999999,
        }
    )
    ueb_ziel_typ: int = field(
        metadata={
            "name": "UEB_ZIEL_TYP",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 2,
        }
    )
    ueb_ziel: int = field(
        metadata={
            "name": "UEB_ZIEL",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 999999,
        }
    )
    ueb_laenge: Optional[int] = field(
        metadata={
            "name": "UEB_LAENGE",
            "type": "Element",
            "min_inclusive": 1,
            "max_inclusive": 81890,
            "nillable": True,
        }
    )
    ueb_fzt: list[UebFzt] = field(
        default_factory=list,
        metadata={
            "name": "UEB_FZT",
            "type": "Element",
        },
    )


@dataclass(kw_only=True)
class RecLid:
    class Meta:
        name = "REC_LID"

    basis_version: int = field(
        metadata={
            "name": "BASIS_VERSION",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 999999999,
        }
    )
    li_nr: int = field(
        metadata={
            "name": "LI_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 999999,
        }
    )
    str_li_var: str = field(
        metadata={
            "name": "STR_LI_VAR",
            "type": "Element",
            "required": True,
            "max_length": 6,
        }
    )

    bereich_nr: int = field(
        metadata={
            "name": "BEREICH_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": 0,
            "max_inclusive": 252,
        }
    )
    li_kuerzel: Optional[str] = field(
        metadata={
            "name": "LI_KUERZEL",
            "type": "Element",
            "max_length": 6,
            "nillable": True,  # todo?
        }
    )
    lidname: Optional[str] = field(
        metadata={
            "name": "LIDNAME",
            "type": "Element",
            "max_length": 40,
            "nillable": True,  # todo?
        }
    )
    routen_art: Optional[int] = field(
        metadata={
            "name": "ROUTEN_ART",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,  # todo?
        }
    )

    lid_verlauf: list[LidVerlauf] = field(
        default_factory=list,
        metadata={
            "name": "LID_VERLAUF",
            "type": "Element",
        },
    )
    rec_frt: list[RecFrt] = field(
        default_factory=list,
        metadata={
            "name": "REC_FRT",
            "type": "Element",
        },
    )


@dataclass(kw_only=True)
class RecUmlauf:
    class Meta:
        name = "REC_UMLAUF"

    basis_version: int = field(
        metadata={
            "name": "BASIS_VERSION",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 999999999,
        }
    )
    tagesart_nr: int = field(
        metadata={
            "name": "TAGESART_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 999,
        }
    )
    um_uid: int = field(
        metadata={
            "name": "UM_UID",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 99999999,
        }
    )
    anf_ort: int = field(
        metadata={
            "name": "ANF_ORT",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 999999,
        }
    )
    anf_onr_typ: int = field(
        metadata={
            "name": "ANF_ONR_TYP",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 2,
        }
    )
    end_ort: int = field(
        metadata={
            "name": "END_ORT",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 999999,
        }
    )
    end_onr_typ: int = field(
        metadata={
            "name": "END_ONR_TYP",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 2,
        }
    )
    fzg_typ_nr: Optional[int] = field(
        default=None,
        metadata={
            "name": "FZG_TYP_NR",
            "type": "Element",
            "min_inclusive": 1,
            "max_inclusive": 252,
            "nillable": True,
        },
    )
    rec_frt: list[RecFrt] = field(
        default_factory=list,
        metadata={
            "name": "REC_FRT",
            "type": "Element",
        },
    )


@dataclass(kw_only=True)
class MengeFzgTyp:
    class Meta:
        name = "MENGE_FZG_TYP"

    basis_version: int = field(
        metadata={
            "name": "BASIS_VERSION",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 999999999,
        }
    )
    fzg_typ_nr: int = field(
        metadata={
            "name": "FZG_TYP_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": 1,
            "max_inclusive": 252,
        }
    )

    fzg_typ_text: Optional[str] = field(
        metadata={
            "name": "FZG_TYP_TEXT",
            "type": "Element",
            "max_length": 40,
            "nillable": True,  # todo?
        }
    )

    str_fzg_typ: Optional[str] = field(
        metadata={
            "name": "STR_FZG_TYP",
            "type": "Element",
            "max_length": 6,
            "nillable": True,  # todo?
        }
    )

    rec_umlauf: list[RecUmlauf] = field(
        default_factory=list,
        metadata={
            "name": "REC_UMLAUF",
            "type": "Element",
        },
    )

    fzg_laenge: Optional[int] = field(
        default=None,
        metadata={
            "name": "FZG_LAENGE",
            "type": "Element",
            "min_inclusive": 0,
            "max_inclusive": 99,
            "nillable": True,
        },
    )

    fzg_hoehe: Optional[int] = field(
        default=None,
        metadata={
            "name": "FZG_HOEHE",
            "type": "Element",
            "min_inclusive": 0,
            "max_inclusive": 999,
            "nillable": True,
        },
    )

    fzg_breite: Optional[int] = field(
        default=None,
        metadata={
            "name": "FZG_BREITE",
            "type": "Element",
            "min_inclusive": 0,
            "max_inclusive": 999,
            "nillable": True,
        },
    )

    verbrauch_distanz: Optional[int] = field(
        default=None,
        metadata={
            "name": "VERBRAUCH_DISTANZ",
            "type": "Element",
            "min_inclusive": 0,
            "max_inclusive": 99999,
            "nillable": True,
        },
    )
