"""This file was (originally!) generated by xsdata, v24.1, on 2024-01-29 15:42:25

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/


J: Ich musste ich die Datei von Hand anpassen, da bspw. manche Attribute als required=True markiert waren, entgegen der richtigen VDV452-Spezifikation.
"""
from dataclasses import dataclass, field
from typing import Optional


@dataclass(kw_only=True)
class BasisVerGueltigkeit:
    class Meta:
        name = "BASIS_VER_GUELTIGKEIT"

    ver_gueltigkeit: int = field(
        metadata={
            "name": "VER_GUELTIGKEIT",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    basis_version: Optional[int] = field(
        metadata={
            "name": "BASIS_VERSION",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )


@dataclass(kw_only=True)
class Fahrzeug:
    class Meta:
        name = "FAHRZEUG"

    basis_version: int = field(
        metadata={
            "name": "BASIS_VERSION",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    fzg_nr: int = field(
        metadata={
            "name": "FZG_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    fzg_typ_nr: Optional[int] = field(
        metadata={
            "name": "FZG_TYP_NR",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    polkenn: Optional[str] = field(
        metadata={
            "name": "POLKENN",
            "type": "Element",
            "max_length": 20,
            "nillable": True,
        }
    )
    unternehmen: Optional[int] = field(
        metadata={
            "name": "UNTERNEHMEN",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )


@dataclass(kw_only=True)
class Firmenkalender:
    class Meta:
        name = "FIRMENKALENDER"

    basis_version: int = field(
        metadata={
            "name": "BASIS_VERSION",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    betriebstag: int = field(
        metadata={
            "name": "BETRIEBSTAG",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    betriebstag_text: Optional[str] = field(
        metadata={
            "name": "BETRIEBSTAG_TEXT",
            "type": "Element",
            "max_length": 40,
            "nillable": True,
        }
    )
    tagesart_nr: Optional[int] = field(
        metadata={
            "name": "TAGESART_NR",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )


@dataclass(kw_only=True)
class FlZoneOrt:
    class Meta:
        name = "FL_ZONE_ORT"

    basis_version: int = field(
        metadata={
            "name": "BASIS_VERSION",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    fl_zone_typ_nr: int = field(
        metadata={
            "name": "FL_ZONE_TYP_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    fl_zone_nr: Optional[int] = field(
        metadata={
            "name": "FL_ZONE_NR",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    onr_typ_nr: Optional[int] = field(
        metadata={
            "name": "ONR_TYP_NR",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    ort_nr: Optional[int] = field(
        metadata={
            "name": "ORT_NR",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )


@dataclass(kw_only=True)
class LidVerlauf:
    class Meta:
        name = "LID_VERLAUF"

    basis_version: int = field(
        metadata={
            "name": "BASIS_VERSION",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    li_lfd_nr: int = field(
        metadata={
            "name": "LI_LFD_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    li_nr: int = field(
        metadata={
            "name": "LI_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    str_li_var: str = field(
        metadata={
            "name": "STR_LI_VAR",
            "type": "Element",
            "required": True,
            "max_length": 6,
        }
    )
    onr_typ_nr: Optional[int] = field(
        metadata={
            "name": "ONR_TYP_NR",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    ort_nr: Optional[int] = field(
        metadata={
            "name": "ORT_NR",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    znr_nr: Optional[int] = field(
        metadata={
            "name": "ZNR_NR",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    anr_nr: Optional[int] = field(
        metadata={
            "name": "ANR_NR",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    einfangbereich: Optional[int] = field(
        metadata={
            "name": "EINFANGBEREICH",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    li_knoten: bool = field(
        metadata={
            "name": "LI_KNOTEN",
            "type": "Element",
            "required": True,
        }
    )
    produktiv: bool = field(
        metadata={
            "name": "PRODUKTIV",
            "type": "Element",
            "required": True,
        }
    )
    # einsteigeverbot: Optional[bool] = field(
    #     metadata={
    #         "name": "EINSTEIGEVERBOT",
    #         "type": "Element"
    #     }
    # )
    # aussteigeverbot: Optional[bool] = field(
    #     metadata={
    #         "name": "AUSSTEIGEVERBOT",
    #         "type": "Element",
    #     }
    # )
    # innerortsverbot: Optional[bool] = field(
    #     metadata={
    #         "name": "INNERORTSVERBOT",
    #         "type": "Element",
    #         "nillable": True,
    #     }
    # )
    bedarfshalt: bool = field(
        metadata={
            "name": "BEDARFSHALT",
            "type": "Element",
            "required": True,
        }
    )


@dataclass(kw_only=True)
class MengeX0020FlaechenZoneTyp:
    class Meta:
        name = "MENGE__x0020_FLAECHEN_ZONE_TYP"

    basis_version: int = field(
        metadata={
            "name": "BASIS_VERSION",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    fl_zone_typ_nr: int = field(
        metadata={
            "name": "FL_ZONE_TYP_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    fl_zone_typ_text: Optional[str] = field(
        metadata={
            "name": "FL_ZONE_TYP_TEXT",
            "type": "Element",
            "max_length": 40,
            "nillable": True,
        }
    )


@dataclass(kw_only=True)
class OrtHztf:
    class Meta:
        name = "ORT_HZTF"

    basis_version: int = field(
        metadata={
            "name": "BASIS_VERSION",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    fgr_nr: int = field(
        metadata={
            "name": "FGR_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    onr_typ_nr: int = field(
        metadata={
            "name": "ONR_TYP_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    ort_nr: int = field(
        metadata={
            "name": "ORT_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    hp_hzt: Optional[int] = field(
        metadata={
            "name": "HP_HZT",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )


@dataclass(kw_only=True)
class RecFrtHzt:
    class Meta:
        name = "REC_FRT_HZT"

    basis_version: int = field(
        metadata={
            "name": "BASIS_VERSION",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    frt_fid: int = field(
        metadata={
            "name": "FRT_FID",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    onr_typ_nr: int = field(
        metadata={
            "name": "ONR_TYP_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    ort_nr: int = field(
        metadata={
            "name": "ORT_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    frt_hzt_zeit: Optional[int] = field(
        metadata={
            "name": "FRT_HZT_ZEIT",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )


@dataclass(kw_only=True)
class RecHp:
    class Meta:
        name = "REC_HP"

    basis_version: int = field(
        metadata={
            "name": "BASIS_VERSION",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    onr_typ_nr: int = field(
        metadata={
            "name": "ONR_TYP_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    ort_nr: int = field(
        metadata={
            "name": "ORT_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    haltepunkt_nr: Optional[int] = field(
        metadata={
            "name": "HALTEPUNKT_NR",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    zusatz_info: Optional[str] = field(
        metadata={
            "name": "ZUSATZ_INFO",
            "type": "Element",
            "max_length": 40,
            "nillable": True,
        }
    )


@dataclass(kw_only=True)
class RecOm:
    class Meta:
        name = "REC_OM"

    basis_version: int = field(
        metadata={
            "name": "BASIS_VERSION",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    onr_typ_nr: int = field(
        metadata={
            "name": "ONR_TYP_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    ort_nr: int = field(
        metadata={
            "name": "ORT_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    orm_kuerzel: Optional[str] = field(
        metadata={
            "name": "ORM_KUERZEL",
            "type": "Element",
            "max_length": 6,
            "nillable": True,
        }
    )
    ormacode: Optional[int] = field(
        metadata={
            "name": "ORMACODE",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    orm_text: Optional[str] = field(
        metadata={
            "name": "ORM_TEXT",
            "type": "Element",
            "max_length": 40,
            "nillable": True,
        }
    )


@dataclass(kw_only=True)
class RecSelZp:
    class Meta:
        name = "REC_SEL_ZP"

    basis_version: int = field(
        metadata={
            "name": "BASIS_VERSION",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    bereich_nr: int = field(
        metadata={
            "name": "BEREICH_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    onr_typ_nr: int = field(
        metadata={
            "name": "ONR_TYP_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    ort_nr: int = field(
        metadata={
            "name": "ORT_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    sel_ziel: int = field(
        metadata={
            "name": "SEL_ZIEL",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    sel_ziel_typ: int = field(
        metadata={
            "name": "SEL_ZIEL_TYP",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    zp_onr: int = field(
        metadata={
            "name": "ZP_ONR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    zp_typ: int = field(
        metadata={
            "name": "ZP_TYP",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    sel_zp_laenge: Optional[int] = field(
        metadata={
            "name": "SEL_ZP_LAENGE",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    zp_lfd_nr: Optional[int] = field(
        metadata={
            "name": "ZP_LFD_NR",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )


@dataclass(kw_only=True)
class RecUms:
    class Meta:
        name = "REC_UMS"

    basis_version: int = field(
        metadata={
            "name": "BASIS_VERSION",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    einan_nr: int = field(
        metadata={
            "name": "EINAN_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    tagesart_nr: int = field(
        metadata={
            "name": "TAGESART_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    ums_beginn: int = field(
        metadata={
            "name": "UMS_BEGINN",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    ums_ende: int = field(
        metadata={
            "name": "UMS_ENDE",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    ums_min: Optional[int] = field(
        metadata={
            "name": "UMS_MIN",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    ums_max: Optional[int] = field(
        metadata={
            "name": "UMS_MAX",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    max_verz_man: Optional[int] = field(
        metadata={
            "name": "MAX_VERZ_MAN",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    max_verz_auto: Optional[int] = field(
        metadata={
            "name": "MAX_VERZ_AUTO",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )


@dataclass(kw_only=True)
class SelFztFeld:
    class Meta:
        name = "SEL_FZT_FELD"

    basis_version: int = field(
        metadata={
            "name": "BASIS_VERSION",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    bereich_nr: int = field(
        metadata={
            "name": "BEREICH_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    fgr_nr: int = field(
        metadata={
            "name": "FGR_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    onr_typ_nr: int = field(
        metadata={
            "name": "ONR_TYP_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    ort_nr: int = field(
        metadata={
            "name": "ORT_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    sel_ziel: int = field(
        metadata={
            "name": "SEL_ZIEL",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    sel_ziel_typ: int = field(
        metadata={
            "name": "SEL_ZIEL_TYP",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    sel_fzt: Optional[int] = field(
        metadata={
            "name": "SEL_FZT",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )


@dataclass(kw_only=True)
class SelFztFeldZp:
    class Meta:
        name = "SEL_FZT_FELD_ZP"

    basis_version: int = field(
        metadata={
            "name": "BASIS_VERSION",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    bereich_nr: int = field(
        metadata={
            "name": "BEREICH_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    fgr_nr: int = field(
        metadata={
            "name": "FGR_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    onr_typ_nr: int = field(
        metadata={
            "name": "ONR_TYP_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    ort_nr: int = field(
        metadata={
            "name": "ORT_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    sel_ziel: int = field(
        metadata={
            "name": "SEL_ZIEL",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    sel_ziel_typ: int = field(
        metadata={
            "name": "SEL_ZIEL_TYP",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    zp_onr: int = field(
        metadata={
            "name": "ZP_ONR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    zp_typ: int = field(
        metadata={
            "name": "ZP_TYP",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    sel_fzt_zp: Optional[int] = field(
        metadata={
            "name": "SEL_FZT_ZP",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )


@dataclass(kw_only=True)
class UebFzt:
    class Meta:
        name = "UEB_FZT"

    basis_version: int = field(
        metadata={
            "name": "BASIS_VERSION",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    bereich_nr: int = field(
        metadata={
            "name": "BEREICH_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    fgr_nr: int = field(
        metadata={
            "name": "FGR_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    onr_typ_nr: int = field(
        metadata={
            "name": "ONR_TYP_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    ort_nr: int = field(
        metadata={
            "name": "ORT_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    ueb_ziel_typ: int = field(
        metadata={
            "name": "UEB_ZIEL_TYP",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    ueb_ziel: int = field(
        metadata={
            "name": "UEB_ZIEL",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    ueb_fahrzeit: Optional[int] = field(
        metadata={
            "name": "UEB_FAHRZEIT",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )


@dataclass(kw_only=True)
class Einzelanschluss:
    class Meta:
        name = "EINZELANSCHLUSS"

    basis_version: int = field(
        metadata={
            "name": "BASIS_VERSION",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    einan_nr: int = field(
        metadata={
            "name": "EINAN_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    anschluss_name: Optional[str] = field(
        metadata={
            "name": "ANSCHLUSS_NAME",
            "type": "Element",
            "max_length": 40,
            "nillable": True,
        }
    )
    anschluss_gruppe: Optional[str] = field(
        metadata={
            "name": "ANSCHLUSS_GRUPPE",
            "type": "Element",
            "max_length": 6,
            "nillable": True,
        }
    )
    leitstellenkennung: Optional[int] = field(
        metadata={
            "name": "LEITSTELLENKENNUNG",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    zub_li_nr: Optional[int] = field(
        metadata={
            "name": "ZUB_LI_NR",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    zub_li_ri_nr: Optional[int] = field(
        metadata={
            "name": "ZUB_LI_RI_NR",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    zub_ort_ref_ort: Optional[int] = field(
        metadata={
            "name": "ZUB_ORT_REF_ORT",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    zub_onr_typ_nr: Optional[int] = field(
        metadata={
            "name": "ZUB_ONR_TYP_NR",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    zub_ort_nr: Optional[int] = field(
        metadata={
            "name": "ZUB_ORT_NR",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    von_ort_ref_ort: Optional[int] = field(
        metadata={
            "name": "VON_ORT_REF_ORT",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    linien_id: Optional[str] = field(
        metadata={
            "name": "LinienID",
            "type": "Element",
            "max_length": 6,
            "nillable": True,
        }
    )
    richtungs_id: Optional[str] = field(
        metadata={
            "name": "RichtungsID",
            "type": "Element",
            "max_length": 6,
            "nillable": True,
        }
    )
    asbid: Optional[str] = field(
        metadata={
            "name": "ASBID",
            "type": "Element",
            "max_length": 10,
            "nillable": True,
        }
    )
    abb_li_nr: Optional[int] = field(
        metadata={
            "name": "ABB_LI_NR",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    abb_li_ri_nr: Optional[int] = field(
        metadata={
            "name": "ABB_LI_RI_NR",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    abb_ort_ref_ort: Optional[int] = field(
        metadata={
            "name": "ABB_ORT_REF_ORT",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    abb_onr_typ_nr: Optional[int] = field(
        metadata={
            "name": "ABB_ONR_TYP_NR",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    abb_ort_nr: Optional[int] = field(
        metadata={
            "name": "ABB_ORT_NR",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    nach_ort_ref_ort: Optional[int] = field(
        metadata={
            "name": "NACH_ORT_REF_ORT",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    rec_ums: list[RecUms] = field(
        default_factory=list,
        metadata={
            "name": "REC_UMS",
            "type": "Element",
        },
    )


@dataclass(kw_only=True)
class FlaechenZone:
    class Meta:
        name = "FLAECHEN_ZONE"

    basis_version: int = field(
        metadata={
            "name": "BASIS_VERSION",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    fl_zone_typ_nr: int = field(
        metadata={
            "name": "FL_ZONE_TYP_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    fl_zone_nr: int = field(
        metadata={
            "name": "FL_ZONE_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    fl_zone_kuerzel: Optional[str] = field(
        metadata={
            "name": "FL_ZONE_KUERZEL",
            "type": "Element",
            "max_length": 8,
            "nillable": True,
        }
    )
    fl_zone_name: Optional[str] = field(
        metadata={
            "name": "FL_ZONE_NAME",
            "type": "Element",
            "max_length": 40,
            "nillable": True,
        }
    )
    fl_amtliche_nr: Optional[str] = field(
        metadata={
            "name": "FL_AMTLICHE_NR",
            "type": "Element",
            "max_length": 20,
            "nillable": True,
        }
    )
    fl_zone_ort: list[FlZoneOrt] = field(
        default_factory=list,
        metadata={
            "name": "FL_ZONE_ORT",
            "type": "Element",
        },
    )
    menge_x0020_flaechen_zone_typ: list[MengeX0020FlaechenZoneTyp] = field(
        default_factory=list,
        metadata={
            "name": "MENGE__x0020_FLAECHEN_ZONE_TYP",
            "type": "Element",
        },
    )


@dataclass(kw_only=True)
class MengeOnrTyp:
    class Meta:
        name = "MENGE_ONR_TYP"

    basis_version: int = field(
        metadata={
            "name": "BASIS_VERSION",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    onr_typ_nr: int = field(
        metadata={
            "name": "ONR_TYP_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    str_onr_typ: Optional[str] = field(
        metadata={
            "name": "STR_ONR_TYP",
            "type": "Element",
            "max_length": 6,
            "nillable": True,
        }
    )
    onr_typ_text: Optional[str] = field(
        metadata={
            "name": "ONR_TYP_TEXT",
            "type": "Element",
            "max_length": 40,
            "nillable": True,
        }
    )
    rec_hp: list[RecHp] = field(
        default_factory=list,
        metadata={
            "name": "REC_HP",
            "type": "Element",
        },
    )
    sel_fzt_feld_zp: list[SelFztFeldZp] = field(
        default_factory=list,
        metadata={
            "name": "SEL_FZT_FELD_ZP",
            "type": "Element",
        },
    )


@dataclass(kw_only=True)
class RecAnr:
    class Meta:
        name = "REC_ANR"

    basis_version: int = field(
        metadata={
            "name": "BASIS_VERSION",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    anr_nr: int = field(
        metadata={
            "name": "ANR_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    anr_text: Optional[str] = field(
        metadata={
            "name": "ANR_TEXT",
            "type": "Element",
            "max_length": 200,
            "nillable": True,
        }
    )
    lid_verlauf: list[LidVerlauf] = field(
        default_factory=list,
        metadata={
            "name": "LID_VERLAUF",
            "type": "Element",
        },
    )


@dataclass(kw_only=True)
class RecFrt:
    class Meta:
        name = "REC_FRT"

    basis_version: int = field(
        metadata={
            "name": "BASIS_VERSION",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    frt_fid: int = field(
        metadata={
            "name": "FRT_FID",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    frt_start: Optional[int] = field(
        metadata={
            "name": "FRT_START",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    li_nr: Optional[int] = field(
        metadata={
            "name": "LI_NR",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    tagesart_nr: Optional[int] = field(
        metadata={
            "name": "TAGESART_NR",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    li_ku_nr: Optional[int] = field(
        metadata={
            "name": "LI_KU_NR",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    fahrtart_nr: Optional[int] = field(
        metadata={
            "name": "FAHRTART_NR",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    fgr_nr: Optional[int] = field(
        metadata={
            "name": "FGR_NR",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    str_li_var: Optional[str] = field(
        metadata={
            "name": "STR_LI_VAR",
            "type": "Element",
            "max_length": 6,
            "nillable": True,
        }
    )
    um_uid: Optional[int] = field(
        metadata={
            "name": "UM_UID",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    zugnr: Optional[int] = field(
        metadata={
            "name": "ZUGNR",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    durchbi_frt_start: bool = field(
        metadata={
            "name": "DURCHBI_FRT_START",
            "type": "Element",
            "required": True,
        }
    )
    durchbi_frt_ende: bool = field(
        metadata={
            "name": "DURCHBI_FRT_ENDE",
            "type": "Element",
            "required": True,
        }
    )
    rec_frt_hzt: list[RecFrtHzt] = field(
        default_factory=list,
        metadata={
            "name": "REC_FRT_HZT",
            "type": "Element",
        },
    )


@dataclass(kw_only=True)
class RecOrt:
    class Meta:
        name = "REC_ORT"

    basis_version: int = field(
        metadata={
            "name": "BASIS_VERSION",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    onr_typ_nr: int = field(
        metadata={
            "name": "ONR_TYP_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    ort_nr: int = field(
        metadata={
            "name": "ORT_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    ort_name: Optional[str] = field(
        metadata={
            "name": "ORT_NAME",
            "type": "Element",
            "max_length": 40,
            "nillable": True,
        }
    )
    ort_ref_ort: Optional[int] = field(
        metadata={
            "name": "ORT_REF_ORT",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    ort_ref_ort_typ: Optional[int] = field(
        metadata={
            "name": "ORT_REF_ORT_TYP",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    ort_ref_ort_langnr: Optional[int] = field(
        metadata={
            "name": "ORT_REF_ORT_LANGNR",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    ort_ref_ort_kuerzel: Optional[str] = field(
        metadata={
            "name": "ORT_REF_ORT_KUERZEL",
            "type": "Element",
            "max_length": 8,
            "nillable": True,
        }
    )
    ort_ref_ort_name: Optional[str] = field(
        metadata={
            "name": "ORT_REF_ORT_NAME",
            "type": "Element",
            "max_length": 40,
            "nillable": True,
        }
    )
    zone_wabe_nr: Optional[int] = field(
        metadata={
            "name": "ZONE_WABE_NR",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    ort_pos_laenge: Optional[int] = field(
        metadata={
            "name": "ORT_POS_LAENGE",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    ort_pos_breite: Optional[int] = field(
        metadata={
            "name": "ORT_POS_BREITE",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    ort_pos_hoehe: Optional[int] = field(
        metadata={
            "name": "ORT_POS_HOEHE",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    ort_richtung: Optional[int] = field(
        metadata={
            "name": "ORT_RICHTUNG",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    hast_nr_lokal: Optional[int] = field(
        metadata={
            "name": "HAST_NR_LOKAL",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    hst_nr_national: Optional[int] = field(
        metadata={
            "name": "HST_NR_NATIONAL",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    hst_nr_international: Optional[str] = field(
        metadata={
            "name": "HST_NR_INTERNATIONAL",
            "type": "Element",
            "max_length": 30,
            "nillable": True,
        }
    )
    lid_verlauf: list[LidVerlauf] = field(
        default_factory=list,
        metadata={
            "name": "LID_VERLAUF",
            "type": "Element",
        },
    )
    ort_hztf: list[OrtHztf] = field(
        default_factory=list,
        metadata={
            "name": "ORT_HZTF",
            "type": "Element",
        },
    )
    rec_hp: list[RecHp] = field(
        default_factory=list,
        metadata={
            "name": "REC_HP",
            "type": "Element",
        },
    )
    rec_om: list[RecOm] = field(
        default_factory=list,
        metadata={
            "name": "REC_OM",
            "type": "Element",
        },
    )


@dataclass(kw_only=True)
class RecSel:
    class Meta:
        name = "REC_SEL"

    basis_version: int = field(
        metadata={
            "name": "BASIS_VERSION",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    bereich_nr: int = field(
        metadata={
            "name": "BEREICH_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    onr_typ_nr: int = field(
        metadata={
            "name": "ONR_TYP_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    ort_nr: int = field(
        metadata={
            "name": "ORT_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    sel_ziel: int = field(
        metadata={
            "name": "SEL_ZIEL",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    sel_ziel_typ: int = field(
        metadata={
            "name": "SEL_ZIEL_TYP",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    sel_laenge: Optional[int] = field(
        metadata={
            "name": "SEL_LAENGE",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    rec_sel_zp: list[RecSelZp] = field(
        default_factory=list,
        metadata={
            "name": "REC_SEL_ZP",
            "type": "Element",
        },
    )
    sel_fzt_feld: list[SelFztFeld] = field(
        default_factory=list,
        metadata={
            "name": "SEL_FZT_FELD",
            "type": "Element",
        },
    )
    sel_fzt_feld_zp: list[SelFztFeldZp] = field(
        default_factory=list,
        metadata={
            "name": "SEL_FZT_FELD_ZP",
            "type": "Element",
        },
    )


@dataclass(kw_only=True)
class RecUeb:
    class Meta:
        name = "REC_UEB"

    basis_version: int = field(
        metadata={
            "name": "BASIS_VERSION",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    bereich_nr: int = field(
        metadata={
            "name": "BEREICH_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    onr_typ_nr: int = field(
        metadata={
            "name": "ONR_TYP_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    ort_nr: int = field(
        metadata={
            "name": "ORT_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    ueb_ziel_typ: int = field(
        metadata={
            "name": "UEB_ZIEL_TYP",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    ueb_ziel: int = field(
        metadata={
            "name": "UEB_ZIEL",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    ueb_laenge: Optional[int] = field(
        metadata={
            "name": "UEB_LAENGE",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    ueb_fzt: list[UebFzt] = field(
        default_factory=list,
        metadata={
            "name": "UEB_FZT",
            "type": "Element",
        },
    )


@dataclass(kw_only=True)
class RecZnr:
    class Meta:
        name = "REC_ZNR"

    basis_version: int = field(
        metadata={
            "name": "BASIS_VERSION",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    znr_nr: int = field(
        metadata={
            "name": "ZNR_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    faherekurztext: Optional[str] = field(
        metadata={
            "name": "FAHEREKURZTEXT",
            "type": "Element",
            "max_length": 44,
            "nillable": True,
        }
    )
    seitentext: Optional[str] = field(
        metadata={
            "name": "SEITENTEXT",
            "type": "Element",
            "max_length": 160,
            "nillable": True,
        }
    )
    znr_text: Optional[str] = field(
        metadata={
            "name": "ZNR_TEXT",
            "type": "Element",
            "max_length": 160,
            "nillable": True,
        }
    )
    znr_code: Optional[str] = field(
        metadata={
            "name": "ZNR_CODE",
            "type": "Element",
            "max_length": 68,
            "nillable": True,
        }
    )
    lid_verlauf: list[LidVerlauf] = field(
        default_factory=list,
        metadata={
            "name": "LID_VERLAUF",
            "type": "Element",
        },
    )


@dataclass(kw_only=True)
class ZulVerkehrsbetrieb:
    class Meta:
        name = "ZUL_VERKEHRSBETRIEB"

    basis_version: int = field(
        metadata={
            "name": "BASIS_VERSION",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    unternehmen: int = field(
        metadata={
            "name": "UNTERNEHMEN",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    abk_unternehmen: Optional[str] = field(
        metadata={
            "name": "ABK_UNTERNEHMEN",
            "type": "Element",
            "max_length": 6,
            "nillable": True,
        }
    )
    betriebsgebiet_bez: Optional[str] = field(
        metadata={
            "name": "BETRIEBSGEBIET_BEZ",
            "type": "Element",
            "max_length": 40,
            "nillable": True,
        }
    )
    fahrzeug: list[Fahrzeug] = field(
        default_factory=list,
        metadata={
            "name": "FAHRZEUG",
            "type": "Element",
        },
    )


@dataclass(kw_only=True)
class MengeBereich:
    class Meta:
        name = "MENGE_BEREICH"

    basis_version: int = field(
        metadata={
            "name": "BASIS_VERSION",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    bereich_nr: int = field(
        metadata={
            "name": "BEREICH_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    str_bereich: Optional[str] = field(
        metadata={
            "name": "STR_BEREICH",
            "type": "Element",
            "max_length": 6,
            "nillable": True,
        }
    )
    bereich_text: Optional[str] = field(
        metadata={
            "name": "BEREICH_TEXT",
            "type": "Element",
            "max_length": 40,
            "nillable": True,
        }
    )
    rec_sel: list[RecSel] = field(
        default_factory=list,
        metadata={
            "name": "REC_SEL",
            "type": "Element",
        },
    )
    rec_ueb: list[RecUeb] = field(
        default_factory=list,
        metadata={
            "name": "REC_UEB",
            "type": "Element",
        },
    )
    sel_fzt_feld_zp: list[SelFztFeldZp] = field(
        default_factory=list,
        metadata={
            "name": "SEL_FZT_FELD_ZP",
            "type": "Element",
        },
    )


@dataclass(kw_only=True)
class MengeFahrtart:
    class Meta:
        name = "MENGE_FAHRTART"

    basis_version: int = field(
        metadata={
            "name": "BASIS_VERSION",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    fahrtart_nr: int = field(
        metadata={
            "name": "FAHRTART_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    str_fahrtart: Optional[str] = field(
        metadata={
            "name": "STR_FAHRTART",
            "type": "Element",
            "max_length": 6,
            "nillable": True,
        }
    )
    rec_frt: list[RecFrt] = field(
        default_factory=list,
        metadata={
            "name": "REC_FRT",
            "type": "Element",
        },
    )


@dataclass(kw_only=True)
class MengeFgr:
    class Meta:
        name = "MENGE_FGR"

    basis_version: int = field(
        metadata={
            "name": "BASIS_VERSION",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    fgr_nr: int = field(
        metadata={
            "name": "FGR_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    fgr_text: Optional[str] = field(
        metadata={
            "name": "FGR_TEXT",
            "type": "Element",
            "max_length": 40,
            "nillable": True,
        }
    )
    ort_hztf: list[OrtHztf] = field(
        default_factory=list,
        metadata={
            "name": "ORT_HZTF",
            "type": "Element",
        },
    )
    rec_frt: list[RecFrt] = field(
        default_factory=list,
        metadata={
            "name": "REC_FRT",
            "type": "Element",
        },
    )
    sel_fzt_feld: list[SelFztFeld] = field(
        default_factory=list,
        metadata={
            "name": "SEL_FZT_FELD",
            "type": "Element",
        },
    )
    sel_fzt_feld_zp: list[SelFztFeldZp] = field(
        default_factory=list,
        metadata={
            "name": "SEL_FZT_FELD_ZP",
            "type": "Element",
        },
    )
    ueb_fzt: list[UebFzt] = field(
        default_factory=list,
        metadata={
            "name": "UEB_FZT",
            "type": "Element",
        },
    )


@dataclass(kw_only=True)
class MengeOrtTyp:
    class Meta:
        name = "MENGE_ORT_TYP"

    basis_version: int = field(
        metadata={
            "name": "BASIS_VERSION",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    ort_typ_nr: int = field(
        metadata={
            "name": "ORT_TYP_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    ort_typ_text: Optional[str] = field(
        metadata={
            "name": "ORT_TYP_TEXT",
            "type": "Element",
            "max_length": 40,
            "nillable": True,
        }
    )
    rec_ort: list[RecOrt] = field(
        default_factory=list,
        metadata={
            "name": "REC_ORT",
            "type": "Element",
        },
    )


@dataclass(kw_only=True)
class RecLid:
    class Meta:
        name = "REC_LID"

    basis_version: int = field(
        metadata={
            "name": "BASIS_VERSION",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    li_nr: int = field(
        metadata={
            "name": "LI_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    str_li_var: str = field(
        metadata={
            "name": "STR_LI_VAR",
            "type": "Element",
            "required": True,
            "max_length": 6,
        }
    )
    routen_nr: Optional[int] = field(
        metadata={
            "name": "ROUTEN_NR",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    li_ri_nr: Optional[int] = field(
        metadata={
            "name": "LI_RI_NR",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    bereich_nr: Optional[int] = field(
        metadata={
            "name": "BEREICH_NR",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    li_kuerzel: Optional[str] = field(
        metadata={
            "name": "LI_KUERZEL",
            "type": "Element",
            "max_length": 6,
            "nillable": True,
        }
    )
    lidname: Optional[str] = field(
        metadata={
            "name": "LIDNAME",
            "type": "Element",
            "max_length": 40,
            "nillable": True,
        }
    )
    routen_art: Optional[int] = field(
        metadata={
            "name": "ROUTEN_ART",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    linien_code: Optional[int] = field(
        metadata={
            "name": "LINIEN_CODE",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    einzelanschluss: list[Einzelanschluss] = field(
        default_factory=list,
        metadata={
            "name": "EINZELANSCHLUSS",
            "type": "Element",
            "sequence": 1,
        },
    )
    lid_verlauf: list[LidVerlauf] = field(
        default_factory=list,
        metadata={
            "name": "LID_VERLAUF",
            "type": "Element",
        },
    )
    rec_frt: list[RecFrt] = field(
        default_factory=list,
        metadata={
            "name": "REC_FRT",
            "type": "Element",
        },
    )


@dataclass(kw_only=True)
class RecUmlauf:
    class Meta:
        name = "REC_UMLAUF"

    basis_version: int = field(
        metadata={
            "name": "BASIS_VERSION",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    tagesart_nr: int = field(
        metadata={
            "name": "TAGESART_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    um_uid: int = field(
        metadata={
            "name": "UM_UID",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    anf_ort: Optional[int] = field(
        metadata={
            "name": "ANF_ORT",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    anf_onr_typ: Optional[int] = field(
        metadata={
            "name": "ANF_ONR_TYP",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    end_ort: Optional[int] = field(
        metadata={
            "name": "END_ORT",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    end_onr_typ: Optional[int] = field(
        metadata={
            "name": "END_ONR_TYP",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    fzg_typ_nr: Optional[int] = field(
        metadata={
            "name": "FZG_TYP_NR",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    rec_frt: list[RecFrt] = field(
        default_factory=list,
        metadata={
            "name": "REC_FRT",
            "type": "Element",
        },
    )


@dataclass(kw_only=True)
class MengeFzgTyp:
    class Meta:
        name = "MENGE_FZG_TYP"

    basis_version: int = field(
        metadata={
            "name": "BASIS_VERSION",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    fzg_typ_nr: int = field(
        metadata={
            "name": "FZG_TYP_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    fzg_laenge: Optional[int] = field(
        metadata={
            "name": "FZG_LAENGE",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    fzg_typ_sitz: Optional[int] = field(
        metadata={
            "name": "FZG_TYP_SITZ",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    fzg_typ_steh: Optional[int] = field(
        metadata={
            "name": "FZG_TYP_STEH",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    fzg_typ_text: Optional[str] = field(
        metadata={
            "name": "FZG_TYP_TEXT",
            "type": "Element",
            "max_length": 40,
            "nillable": True,
        }
    )
    sonder_platz: Optional[int] = field(
        metadata={
            "name": "SONDER_PLATZ",
            "type": "Element",
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
            "nillable": True,
        }
    )
    str_fzg_typ: Optional[str] = field(
        metadata={
            "name": "STR_FZG_TYP",
            "type": "Element",
            "max_length": 6,
            "nillable": True,
        }
    )
    fahrzeug: list[Fahrzeug] = field(
        default_factory=list,
        metadata={
            "name": "FAHRZEUG",
            "type": "Element",
        },
    )
    rec_umlauf: list[RecUmlauf] = field(
        default_factory=list,
        metadata={
            "name": "REC_UMLAUF",
            "type": "Element",
        },
    )


@dataclass(kw_only=True)
class MengeTagesart:
    class Meta:
        name = "MENGE_TAGESART"

    basis_version: int = field(
        metadata={
            "name": "BASIS_VERSION",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    tagesart_nr: int = field(
        metadata={
            "name": "TAGESART_NR",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    tagesart_text: Optional[str] = field(
        metadata={
            "name": "TAGESART_TEXT",
            "type": "Element",
            "max_length": 40,
            "nillable": True,
        }
    )
    firmenkalender: list[Firmenkalender] = field(
        default_factory=list,
        metadata={
            "name": "FIRMENKALENDER",
            "type": "Element",
        },
    )
    rec_umlauf: list[RecUmlauf] = field(
        default_factory=list,
        metadata={
            "name": "REC_UMLAUF",
            "type": "Element",
        },
    )


@dataclass(kw_only=True)
class MengeBasisVersionen:
    class Meta:
        name = "MENGE_BASIS_VERSIONEN"

    basis_version: int = field(
        metadata={
            "name": "BASIS_VERSION",
            "type": "Element",
            "required": True,
            "min_inclusive": -2147483648,
            "max_inclusive": 2147483647,
        }
    )
    basis_version_text: Optional[str] = field(
        metadata={
            "name": "BASIS_VERSION_TEXT",
            "type": "Element",
            "max_length": 40,
            "nillable": True,
        }
    )
    basis_ver_gueltigkeit: list[BasisVerGueltigkeit] = field(
        default_factory=list,
        metadata={
            "name": "BASIS_VER_GUELTIGKEIT",
            "type": "Element",
        },
    )
    menge_x0020_flaechen_zone_typ: list[MengeX0020FlaechenZoneTyp] = field(
        default_factory=list,
        metadata={
            "name": "MENGE__x0020_FLAECHEN_ZONE_TYP",
            "type": "Element",
        },
    )
    menge_bereich: list[MengeBereich] = field(
        default_factory=list,
        metadata={
            "name": "MENGE_BEREICH",
            "type": "Element",
        },
    )
    menge_fzg_typ: list[MengeFzgTyp] = field(
        default_factory=list,
        metadata={
            "name": "MENGE_FZG_TYP",
            "type": "Element",
        },
    )
    menge_onr_typ: list[MengeOnrTyp] = field(
        default_factory=list,
        metadata={
            "name": "MENGE_ONR_TYP",
            "type": "Element",
        },
    )
    menge_ort_typ: list[MengeOrtTyp] = field(
        default_factory=list,
        metadata={
            "name": "MENGE_ORT_TYP",
            "type": "Element",
        },
    )
    menge_tagesart: list[MengeTagesart] = field(
        default_factory=list,
        metadata={
            "name": "MENGE_TAGESART",
            "type": "Element",
        },
    )
    rec_lid: list[RecLid] = field(
        default_factory=list,
        metadata={
            "name": "REC_LID",
            "type": "Element",
        },
    )
    sel_fzt_feld_zp: list[SelFztFeldZp] = field(
        default_factory=list,
        metadata={
            "name": "SEL_FZT_FELD_ZP",
            "type": "Element",
        },
    )
    zul_verkehrsbetrieb: list[ZulVerkehrsbetrieb] = field(
        default_factory=list,
        metadata={
            "name": "ZUL_VERKEHRSBETRIEB",
            "type": "Element",
        },
    )
