"""
Writing a :class:`~eflips.ingest.bvgxml._schedule.Schedule` to the database.

This is a single insert-only pass in dependency order. Nothing here decides anything: the
schedule handed to :func:`emit` is already final, so there is no update pass, no merging of
stations after the fact and no deletion of rotations that should not have been created.
"""
import logging
import os
import sqlite3
from typing import Callable, Dict, Optional

import eflips.model
import psycopg2
from sqlalchemy.orm import Session

from eflips.ingest.bvgxml._network import StationRef
from eflips.ingest.bvgxml._routes import ResolvedRoute
from eflips.ingest.bvgxml._schedule import Schedule

#: Standard 12 m solo city bus. BVG-XML carries no vehicle dimensions, but eflips-model
#: requires all three to be set together and django-simba requires them to be non-null, so
#: auto-generated rows get a plausible shape for the user to override.
_DEFAULT_VEHICLE_LENGTH_M = 12.0
_DEFAULT_VEHICLE_WIDTH_M = 2.55
_DEFAULT_VEHICLE_HEIGHT_M = 3.4

#: Roughly how many progress updates each of the two long loops below should produce. A
#: fixed stride cannot do this: at ``index % 200`` a 277-rotation import reports twice and
#: then goes quiet for the rest of the write.
_UPDATES_PER_LOOP = 50


def _stride(count: int) -> int:
    """A reporting stride that gives about :data:`_UPDATES_PER_LOOP` updates over ``count``."""
    return max(1, count // _UPDATES_PER_LOOP)


def emit(
    schedule: Schedule,
    scenario_id: int,
    session: Session,
    progress_callback: Optional[Callable[[float], None]] = None,
) -> None:
    """
    Write the schedule into an open session. The caller commits.

    :param schedule: the finished schedule
    :param scenario_id: the scenario to write into
    :param session: an open database session
    :param progress_callback: called with a value in ``[0, 1]`` as the write progresses
    """
    logger = logging.getLogger(__name__)
    network = schedule.network

    def report(fraction: float) -> None:
        if progress_callback:
            progress_callback(min(1.0, max(0.0, fraction)))

    lines: Dict[str, eflips.model.Line] = {}
    for name in schedule.lines:
        line = eflips.model.Line(scenario_id=scenario_id, name=name)
        session.add(line)
        lines[name] = line

    vehicle_types: Dict[str, eflips.model.VehicleType] = {}
    for name in schedule.vehicle_types:
        vehicle_type = eflips.model.VehicleType(
            scenario_id=scenario_id,
            name=f"Auto-Generated by XML Importer for {name}",
            name_short=name,
            battery_capacity=1000,
            charging_curve=[[0, 150], [1, 150]],
            opportunity_charging_capable=True,
            length=_DEFAULT_VEHICLE_LENGTH_M,
            width=_DEFAULT_VEHICLE_WIDTH_M,
            height=_DEFAULT_VEHICLE_HEIGHT_M,
        )
        session.add(vehicle_type)
        vehicle_types[name] = vehicle_type
    report(0.05)

    stations: Dict[StationRef, eflips.model.Station] = {}
    for ref in schedule.stations:
        info = network.stations[ref]
        station = eflips.model.Station(
            scenario_id=scenario_id,
            name=info.name,
            name_short=info.name_short,
            is_electrified=False,
            geom=network.geom_of_station(ref),
        )
        session.add(station)
        stations[ref] = station
    report(0.15)

    # Both loops below flush on the way rather than once at the end. The rows have to reach
    # the database at some point, and spreading the work out is what makes the progress
    # honest: with a single flush at the end, the largest single piece of the whole write
    # happened after the last update, and a full-city import sat at 95 % for minutes.
    routes: Dict[int, eflips.model.Route] = {}
    stride = _stride(len(schedule.routes))
    for index, resolved in enumerate(schedule.routes):
        routes[id(resolved)] = _emit_route(resolved, scenario_id, lines, stations, schedule, session)
        if (index + 1) % stride == 0:
            session.flush()
            report(0.15 + 0.2 * (index + 1) / len(schedule.routes))
    session.flush()
    report(0.35)

    stride = _stride(len(schedule.rotations))
    for index, rotation in enumerate(schedule.rotations):
        db_rotation = eflips.model.Rotation(
            scenario_id=scenario_id,
            name=rotation.name,
            vehicle_type=vehicle_types[rotation.vehicle_type],
            allow_opportunity_charging=True,
        )
        session.add(db_rotation)
        for trip in rotation.trips:
            db_trip = eflips.model.Trip(
                scenario_id=scenario_id,
                route=routes[id(trip.route)],
                rotation=db_rotation,
                departure_time=trip.departure,
                arrival_time=trip.arrival,
                trip_type=(eflips.model.TripType.EMPTY if trip.is_deadhead else eflips.model.TripType.PASSENGER),
            )
            for stop in trip.stops:
                db_trip.stop_times.append(
                    eflips.model.StopTime(
                        scenario_id=scenario_id,
                        station=stations[stop.station],
                        arrival_time=stop.arrival,
                        dwell_duration=stop.dwell,
                    )
                )
            session.add(db_trip)
        if (index + 1) % stride == 0:
            session.flush()
            report(0.35 + 0.65 * (index + 1) / len(schedule.rotations))

    session.flush()
    report(1.0)
    logger.info("Wrote scenario %d to the session; the caller must commit.", scenario_id)


def _emit_route(
    resolved: ResolvedRoute,
    scenario_id: int,
    lines: Dict[str, eflips.model.Line],
    stations: Dict[StationRef, eflips.model.Station],
    schedule: Schedule,
    session: Session,
) -> eflips.model.Route:
    route = eflips.model.Route(
        scenario_id=scenario_id,
        departure_station=stations[resolved.departure.station],
        arrival_station=stations[resolved.arrival.station],
        line=lines[resolved.shape.line],
        name=resolved.name,
        name_short=resolved.name_short,
        headsign=resolved.headsign,
        distance=resolved.distance_m,
        geom=None,
    )
    session.add(route)
    for stop in resolved.stops:
        session.add(
            eflips.model.AssocRouteStation(
                scenario_id=scenario_id,
                route=route,
                station=stations[stop.station],
                # The specific platform this route calls at, not the station's centre.
                location=schedule.network.geom_of_point(stop.grid_point),
                elapsed_distance=stop.elapsed_distance_m,
            )
        )
    return route


def fix_max_sequence(database_url: str) -> None:
    """
    Set each table's id sequence past the highest id in use.

    Kept from the previous implementation: a database that was populated by something which
    assigned ids explicitly (an earlier import, or Django fixtures) leaves its sequences
    behind, and the next insert then collides.

    :param database_url: the database to fix
    """
    TABLES = [
        "Scenario",
        "Plan",
        "Process",
        "BatteryType",
        "VehicleClass",
        "Line",
        "Station",
        "Depot",
        "AssocPlanProcess",
        "VehicleType",
        "Route",
        "Area",
        "Vehicle",
        "AssocVehicleTypeVehicleClass",
        "AssocRouteStation",
        "AssocAreaProcess",
        "Rotation",
        "Trip",
        "Event",
        "StopTime",
    ]
    conn: "psycopg2.extensions.connection | sqlite3.Connection"
    if database_url.startswith("postgis") or database_url.startswith("postgres"):
        KEY_NAME = "id"
        conn = psycopg2.connect(database_url)
        conn.autocommit = True
        for table_name in TABLES:
            with conn.cursor() as cur:
                # Discover the actual sequence rather than assuming the SQLAlchemy naming
                # convention. Django creates sequences like "<app>_<model>_id_seq" even
                # when the table is named "Scenario". pg_get_serial_sequence parses its
                # first argument as an SQL identifier, so PascalCase names must be quoted.
                cur.execute("SELECT pg_get_serial_sequence(%s, %s)", (f'"{table_name}"', KEY_NAME))
                row = cur.fetchone()
                sequence = row[0] if row is not None else None
                if sequence is None:
                    continue
                cur.execute(f'SELECT MAX("{KEY_NAME}") FROM "{table_name}"')
                res = cur.fetchone()
                max_id = res[0] if res is not None else None
                if max_id is not None:
                    cur.execute(f"ALTER SEQUENCE {sequence} RESTART WITH {max_id + 1}")
                    cur.execute(f"SELECT NEXTVAL('{sequence}')")
                    res = cur.fetchone()
                    new_max_id = res[0] if res is not None else None
                    if new_max_id is None or new_max_id <= max_id:
                        raise ValueError(f"Sequence {sequence} did not restart properly; it is at {new_max_id}.")
        conn.close()
    elif database_url.startswith("sqlite") or database_url.startswith("spatialite"):
        file_name = database_url.split("///")[-1]
        if file_name == ":memory:":
            raise ValueError("Cannot fix max sequence on in-memory SQLite database")
        if not os.path.exists(file_name):
            raise ValueError(f"Database file {file_name} does not exist")

        conn = sqlite3.connect(file_name)
        conn.isolation_level = None  # autocommit mode
        cursor = conn.cursor()
        for table_name in TABLES:
            cursor.execute(f'SELECT MAX(id) FROM "{table_name}"')
            res = cursor.fetchone()
            max_id = res[0] if res is not None else None
            if max_id is not None:
                cursor.execute(f'UPDATE sqlite_sequence SET seq = {max_id + 1} WHERE name = "{table_name}"')
        conn.close()
    else:
        raise ValueError(f"Database type not supported: {database_url}")
